/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pageSettings';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ng2-translate/src/translate.service';
import * as import10 from '../../db/component';
import * as import11 from '../../providers/page';
import * as import12 from '../../providers/ga';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import29 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import30 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/option/option.ngfactory';
import * as import32 from 'ng2-translate/src/translate.pipe';
import * as import33 from 'ionic-angular/config/config';
import * as import34 from '@angular/core/src/linker/element_ref';
import * as import35 from 'ionic-angular/navigation/view-controller';
import * as import36 from 'ionic-angular/components/app/app';
import * as import37 from 'ionic-angular/components/menu/menu-controller';
import * as import38 from 'ionic-angular/components/toolbar/toolbar';
import * as import39 from 'ionic-angular/util/keyboard';
import * as import40 from '@angular/core/src/zone/ng_zone';
import * as import41 from 'ionic-angular/components/tabs/tabs';
import * as import42 from 'ionic-angular/gestures/gesture-controller';
import * as import43 from 'ionic-angular/util/form';
import * as import44 from 'ionic-angular/components/icon/icon';
import * as import45 from 'ionic-angular/components/button/button';
import * as import46 from 'ionic-angular/components/menu/menu-toggle';
import * as import47 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import48 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import49 from 'ionic-angular/components/navbar/navbar';
import * as import50 from 'ionic-angular/components/label/label';
import * as import51 from 'ionic-angular/components/option/option';
import * as import52 from 'ionic-angular/components/select/select';
import * as import53 from '@angular/forms/src/directives/control_value_accessor';
import * as import54 from '@angular/forms/src/directives/ng_model';
import * as import55 from '@angular/forms/src/directives/ng_control';
import * as import56 from '@angular/forms/src/directives/ng_control_status';
import * as import57 from 'ionic-angular/components/item/item';
import * as import58 from 'ionic-angular/components/list/list';
import * as import59 from 'ionic-angular/components/grid/grid';
import * as import60 from 'ionic-angular/components/content/content';
export class Wrapper_PageSettings {
  context:import0.PageSettings;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.PageSettings(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PageSettings_Host:import2.RenderComponentType = (null as any);
class _View_PageSettings_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PageSettings_0_4:Wrapper_PageSettings;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSettings_Host0,renderType_PageSettings_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-pageSettings',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageSettings0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageSettings_0_4 = new Wrapper_PageSettings(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.TranslateService),this.parentInjector.get(import10.WhatsSizeDatabase),this.parentInjector.get(import11.PageProvider),this.parentInjector.get(import12.GoogleAnalyticsProvider));
    this._appEl_0.initComponent(this._PageSettings_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PageSettings_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PageSettings) && (0 === requestNodeIndex))) { return this._PageSettings_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PageSettings_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PageSettings_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PageSettings_Host === (null as any))) { (renderType_PageSettings_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PageSettings_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageSettingsNgFactory:import14.ComponentFactory<import0.PageSettings> = new import14.ComponentFactory<import0.PageSettings>('page-pageSettings',viewFactory_PageSettings_Host0,import0.PageSettings);
const styles_PageSettings:any[] = ([] as any[]);
var renderType_PageSettings:import2.RenderComponentType = (null as any);
class _View_PageSettings0 extends import1.AppView<import0.PageSettings> {
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import17.Wrapper_Button;
  _MenuToggle_4_5:import18.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import19.Wrapper_ToolbarItem;
  _query_Button_4_0:import20.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import21.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import22.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import23.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _Grid_16_3:import24.Wrapper_Grid;
  _text_17:any;
  _el_18:any;
  _Row_18_3:import24.Wrapper_Row;
  _text_19:any;
  _el_20:any;
  _Col_20_3:import24.Wrapper_Col;
  _text_21:any;
  _el_22:any;
  _List_22_3:import25.Wrapper_List;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import26.Wrapper_Item;
  _ItemContent_24_5:import26.Wrapper_ItemContent;
  _query_Label_24_0:import20.QueryList<any>;
  _query_Button_24_1:import20.QueryList<any>;
  _query_Icon_24_2:import20.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Label_26_3:import27.Wrapper_Label;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _Select_29_4:import28.Wrapper_Select;
  _NG_VALUE_ACCESSOR_29_5:any[];
  _NgModel_29_6:import29.Wrapper_NgModel;
  _NgControl_29_7:any;
  _NgControlStatus_29_8:import30.Wrapper_NgControlStatus;
  _query_Option_29_0:import20.QueryList<any>;
  _text_30:any;
  _el_31:any;
  _Option_31_3:import31.Wrapper_Option;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Option_34_3:import31.Wrapper_Option;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _Item_39_4:import26.Wrapper_Item;
  _ItemContent_39_5:import26.Wrapper_ItemContent;
  _query_Label_39_0:import20.QueryList<any>;
  _query_Button_39_1:import20.QueryList<any>;
  _query_Icon_39_2:import20.QueryList<any>;
  _text_40:any;
  _el_41:any;
  _Label_41_3:import27.Wrapper_Label;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _Select_44_4:import28.Wrapper_Select;
  _NG_VALUE_ACCESSOR_44_5:any[];
  _NgModel_44_6:import29.Wrapper_NgModel;
  _NgControl_44_7:any;
  _NgControlStatus_44_8:import30.Wrapper_NgControlStatus;
  _query_Option_44_0:import20.QueryList<any>;
  _text_45:any;
  _el_46:any;
  _Option_46_3:import31.Wrapper_Option;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _Option_49_3:import31.Wrapper_Option;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _Option_52_3:import31.Wrapper_Option;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _Row_60_3:import24.Wrapper_Row;
  _text_61:any;
  _el_62:any;
  _Col_62_3:import24.Wrapper_Col;
  _text_63:any;
  _el_64:any;
  _List_64_3:import25.Wrapper_List;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import3.AppElement;
  _Item_66_4:import26.Wrapper_Item;
  _ItemContent_66_5:import26.Wrapper_ItemContent;
  _query_Label_66_0:import20.QueryList<any>;
  _query_Button_66_1:import20.QueryList<any>;
  _query_Icon_66_2:import20.QueryList<any>;
  _text_67:any;
  _el_68:any;
  /*private*/ _appEl_68:import3.AppElement;
  _Button_68_4:import17.Wrapper_Button;
  _text_69:any;
  _el_70:any;
  _Icon_70_3:import21.Wrapper_Icon;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  /*private*/ _appEl_73:import3.AppElement;
  _Button_73_4:import17.Wrapper_Button;
  _text_74:any;
  _el_75:any;
  _Icon_75_3:import21.Wrapper_Icon;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _pipe_translate_0:import32.TranslatePipe;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  _pipe_translate_1:import32.TranslatePipe;
  /*private*/ _expr_22:any;
  _pipe_translate_2:import32.TranslatePipe;
  /*private*/ _expr_24:any;
  _pipe_translate_3:import32.TranslatePipe;
  /*private*/ _expr_25:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  _pipe_translate_4:import32.TranslatePipe;
  /*private*/ _expr_38:any;
  _pipe_translate_5:import32.TranslatePipe;
  /*private*/ _expr_40:any;
  _pipe_translate_6:import32.TranslatePipe;
  /*private*/ _expr_42:any;
  /*private*/ _expr_46:any;
  _pipe_translate_7:import32.TranslatePipe;
  /*private*/ _expr_47:any;
  /*private*/ _expr_52:any;
  _pipe_translate_8:import32.TranslatePipe;
  /*private*/ _expr_53:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSettings0,renderType_PageSettings,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import35.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this.renderer.setElementAttribute(this._el_2,'id','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import36.App),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import17.Wrapper_Button('','',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import18.Wrapper_MenuToggle(this.parentInjector.get(import37.MenuController),new import34.ElementRef(this._el_4),this.parentInjector.get(import35.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import19.Wrapper_ToolbarItem(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import38.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import20.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import21.Wrapper_Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import22.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import22.Wrapper_ToolbarTitle(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import38.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Configurações',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import23.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import23.Wrapper_Content(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import36.App),this.parentInjector.get(import39.Keyboard),this.parentInjector.get(import40.NgZone),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import41.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_16_3 = new import24.Wrapper_Grid();
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-row',(null as any));
    this._Row_18_3 = new import24.Wrapper_Row();
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_20,'width-100','');
    this._Col_20_3 = new import24.Wrapper_Col();
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-list',(null as any));
    this._List_22_3 = new import25.Wrapper_List(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import42.GestureController));
    this._text_23 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this._appEl_24 = new import3.AppElement(24,22,this,this._el_24);
    var compView_24:any = import26.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import26.Wrapper_Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import26.Wrapper_ItemContent();
    this._query_Label_24_0 = new import20.QueryList<any>();
    this._query_Button_24_1 = new import20.QueryList<any>();
    this._query_Icon_24_2 = new import20.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_26,'fixed','');
    this._Label_26_3 = new import27.Wrapper_Label(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_26),this.renderer,(null as any),(null as any),'',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this._appEl_29 = new import3.AppElement(29,24,this,this._el_29);
    var compView_29:any = import28.viewFactory_Select0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Select_29_4 = new import28.Wrapper_Select(this.parentInjector.get(import36.App),this.parentInjector.get(import43.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_29),this.renderer,this._Item_24_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_29_5 = [this._Select_29_4.context];
    this._NgModel_29_6 = new import29.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_29_5);
    this._NgControl_29_7 = this._NgModel_29_6.context;
    this._NgControlStatus_29_8 = new import30.Wrapper_NgControlStatus(this._NgControl_29_7);
    this._query_Option_29_0 = new import20.QueryList<any>();
    this._appEl_29.initComponent(this._Select_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_31,'value','pt');
    this._Option_31_3 = new import31.Wrapper_Option(new import34.ElementRef(this._el_31));
    this._text_32 = this.renderer.createText(this._el_31,'',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_34,'value','en');
    this._Option_34_3 = new import31.Wrapper_Option(new import34.ElementRef(this._el_34));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n            ',(null as any));
    compView_29.create(this._Select_29_4.context,([] as any[]),(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_24_0.reset([this._Label_26_3.context]);
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_26]),
      ([] as any[]).concat([
        this._text_25,
        this._text_28,
        this._text_37
      ]
      ),
      ([] as any[]).concat([this._el_29]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_22,'\n\n          ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_22,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','item item-block');
    this._appEl_39 = new import3.AppElement(39,22,this,this._el_39);
    var compView_39:any = import26.viewFactory_Item0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Item_39_4 = new import26.Wrapper_Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_39),this.renderer);
    this._ItemContent_39_5 = new import26.Wrapper_ItemContent();
    this._query_Label_39_0 = new import20.QueryList<any>();
    this._query_Button_39_1 = new import20.QueryList<any>();
    this._query_Icon_39_2 = new import20.QueryList<any>();
    this._appEl_39.initComponent(this._Item_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_41,'fixed','');
    this._Label_41_3 = new import27.Wrapper_Label(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_41),this.renderer,(null as any),(null as any),'',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this._appEl_44 = new import3.AppElement(44,39,this,this._el_44);
    var compView_44:any = import28.viewFactory_Select0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Select_44_4 = new import28.Wrapper_Select(this.parentInjector.get(import36.App),this.parentInjector.get(import43.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_44),this.renderer,this._Item_39_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_44_5 = [this._Select_44_4.context];
    this._NgModel_44_6 = new import29.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_44_5);
    this._NgControl_44_7 = this._NgModel_44_6.context;
    this._NgControlStatus_44_8 = new import30.Wrapper_NgControlStatus(this._NgControl_44_7);
    this._query_Option_44_0 = new import20.QueryList<any>();
    this._appEl_44.initComponent(this._Select_44_4.context,([] as any[]),compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_46,'value','brl');
    this._Option_46_3 = new import31.Wrapper_Option(new import34.ElementRef(this._el_46));
    this._text_47 = this.renderer.createText(this._el_46,'',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_49,'value','eur');
    this._Option_49_3 = new import31.Wrapper_Option(new import34.ElementRef(this._el_49));
    this._text_50 = this.renderer.createText(this._el_49,'',(null as any));
    this._text_51 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_52,'value','usa');
    this._Option_52_3 = new import31.Wrapper_Option(new import34.ElementRef(this._el_52));
    this._text_53 = this.renderer.createText(this._el_52,'',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n            ',(null as any));
    compView_44.create(this._Select_44_4.context,([] as any[]),(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_39_0.reset([this._Label_41_3.context]);
    this._Item_39_4.context.contentLabel = this._query_Label_39_0.first;
    compView_39.create(this._Item_39_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_41]),
      ([] as any[]).concat([
        this._text_40,
        this._text_43,
        this._text_55
      ]
      ),
      ([] as any[]).concat([this._el_44]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_56 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._text_58 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_59 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_16,'ion-row',(null as any));
    this._Row_60_3 = new import24.Wrapper_Row();
    this._text_61 = this.renderer.createText(this._el_60,'\n      ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_62,'width-100','');
    this._Col_62_3 = new import24.Wrapper_Col();
    this._text_63 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_62,'ion-list',(null as any));
    this._List_64_3 = new import25.Wrapper_List(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_64),this.renderer,this.parentInjector.get(import42.GestureController));
    this._text_65 = this.renderer.createText(this._el_64,'\n          ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','item item-block');
    this._appEl_66 = new import3.AppElement(66,64,this,this._el_66);
    var compView_66:any = import26.viewFactory_Item0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Item_66_4 = new import26.Wrapper_Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_66),this.renderer);
    this._ItemContent_66_5 = new import26.Wrapper_ItemContent();
    this._query_Label_66_0 = new import20.QueryList<any>();
    this._query_Button_66_1 = new import20.QueryList<any>();
    this._query_Icon_66_2 = new import20.QueryList<any>();
    this._appEl_66.initComponent(this._Item_66_4.context,([] as any[]),compView_66);
    this._text_67 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_68 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_68,'block','');
    this.renderer.setElementAttribute(this._el_68,'icon-left','');
    this.renderer.setElementAttribute(this._el_68,'ion-button','');
    this.renderer.setElementAttribute(this._el_68,'type','button');
    this._appEl_68 = new import3.AppElement(68,66,this,this._el_68);
    var compView_68:any = import17.viewFactory_Button0(this.viewUtils,this.injector(68),this._appEl_68);
    this._Button_68_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_68),this.renderer);
    this._appEl_68.initComponent(this._Button_68_4.context,([] as any[]),compView_68);
    this._text_69 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_70 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_70,'name','ios-checkmark-circle');
    this.renderer.setElementAttribute(this._el_70,'role','img');
    this._Icon_70_3 = new import21.Wrapper_Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_70),this.renderer);
    this._text_71 = this.renderer.createText((null as any),'',(null as any));
      compView_68.create(this._Button_68_4.context,[([] as any[]).concat([
        this._text_69,
        this._el_70,
        this._text_71
      ]
    )],(null as any));
    this._text_72 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_73 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_73,'block','');
    this.renderer.setElementAttribute(this._el_73,'color','danger');
    this.renderer.setElementAttribute(this._el_73,'icon-left','');
    this.renderer.setElementAttribute(this._el_73,'ion-button','');
    this.renderer.setElementAttribute(this._el_73,'type','button');
    this._appEl_73 = new import3.AppElement(73,66,this,this._el_73);
    var compView_73:any = import17.viewFactory_Button0(this.viewUtils,this.injector(73),this._appEl_73);
    this._Button_73_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_73),this.renderer);
    this._appEl_73.initComponent(this._Button_73_4.context,([] as any[]),compView_73);
    this._text_74 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_75 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_75,'name','return-left');
    this.renderer.setElementAttribute(this._el_75,'role','img');
    this._Icon_75_3 = new import21.Wrapper_Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_75),this.renderer);
    this._text_76 = this.renderer.createText((null as any),'',(null as any));
      compView_73.create(this._Button_73_4.context,[([] as any[]).concat([
        this._text_74,
        this._el_75,
        this._text_76
      ]
    )],(null as any));
    this._text_77 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_66_0.reset(([] as any[]));
    this._Item_66_4.context.contentLabel = this._query_Label_66_0.first;
    compView_66.create(this._Item_66_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_67,
        this._el_68,
        this._text_72,
        this._el_73,
        this._text_77
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_78 = this.renderer.createText(this._el_64,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_62,'\n      ',(null as any));
    this._text_80 = this.renderer.createText(this._el_60,'\n    ',(null as any));
    this._text_81 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_82 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_82
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_29,'ngModelChange',this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_29,'keyup.space',this.eventHandler(this._handle_keyup_space_29_2.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_29_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._pipe_translate_1 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_22 = import7.UNINITIALIZED;
    this._pipe_translate_2 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_24 = import7.UNINITIALIZED;
    this._pipe_translate_3 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_44,'ngModelChange',this.eventHandler(this._handle_ngModelChange_44_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_1.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_44,'keyup.space',this.eventHandler(this._handle_keyup_space_44_2.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_44_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_44_0.bind(this)));
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._pipe_translate_4 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_38 = import7.UNINITIALIZED;
    this._pipe_translate_5 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_40 = import7.UNINITIALIZED;
    this._pipe_translate_6 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_42 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_68,'click',this.eventHandler(this._handle_click_68_0.bind(this)));
    this._expr_46 = import7.UNINITIALIZED;
    this._pipe_translate_7 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_47 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_73,'click',this.eventHandler(this._handle_click_73_0.bind(this)));
    this._expr_52 = import7.UNINITIALIZED;
    this._pipe_translate_8 = new import32.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.ref);
    this._expr_53 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import45.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import46.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import47.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import48.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import49.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import38.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import50.Label) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Label_26_3.context; }
    if (((token === import51.Option) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Option_31_3.context; }
    if (((token === import51.Option) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Option_34_3.context; }
    if (((token === import52.Select) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Select_29_4.context; }
    if (((token === import53.NG_VALUE_ACCESSOR) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NG_VALUE_ACCESSOR_29_5; }
    if (((token === import54.NgModel) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgModel_29_6.context; }
    if (((token === import55.NgControl) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgControl_29_7; }
    if (((token === import56.NgControlStatus) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgControlStatus_29_8.context; }
    if (((token === import57.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Item_24_4.context; }
    if (((token === import57.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ItemContent_24_5.context; }
    if (((token === import50.Label) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Label_41_3.context; }
    if (((token === import51.Option) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Option_46_3.context; }
    if (((token === import51.Option) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Option_49_3.context; }
    if (((token === import51.Option) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Option_52_3.context; }
    if (((token === import52.Select) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Select_44_4.context; }
    if (((token === import53.NG_VALUE_ACCESSOR) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NG_VALUE_ACCESSOR_44_5; }
    if (((token === import54.NgModel) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgModel_44_6.context; }
    if (((token === import55.NgControl) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgControl_44_7; }
    if (((token === import56.NgControlStatus) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgControlStatus_44_8.context; }
    if (((token === import57.Item) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Item_39_4.context; }
    if (((token === import57.ItemContent) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._ItemContent_39_5.context; }
    if (((token === import58.List) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._List_22_3.context; }
    if (((token === import59.Col) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Col_20_3.context; }
    if (((token === import59.Row) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Row_18_3.context; }
    if (((token === import44.Icon) && (70 === requestNodeIndex))) { return this._Icon_70_3.context; }
    if (((token === import45.Button) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Button_68_4.context; }
    if (((token === import44.Icon) && (75 === requestNodeIndex))) { return this._Icon_75_3.context; }
    if (((token === import45.Button) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Button_73_4.context; }
    if (((token === import57.Item) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._Item_66_4.context; }
    if (((token === import57.ItemContent) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._ItemContent_66_5.context; }
    if (((token === import58.List) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._List_64_3.context; }
    if (((token === import59.Col) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Col_62_3.context; }
    if (((token === import59.Row) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._Row_60_3.context; }
    if (((token === import59.Grid) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Grid_16_3.context; }
    if (((token === import60.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_6_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._Grid_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._Row_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._Col_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._List_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._ItemContent_24_5.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Label_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Select_29_4.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_14:any = this.context.model.lang;
    this._NgModel_29_6.check_model(currVal_14,throwOnChange,false);
    this._NgModel_29_6.detectChangesInternal(this,this._el_29,throwOnChange);
    this._NgControlStatus_29_8.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_21:any = 'pt';
    this._Option_31_3.check_value(currVal_21,throwOnChange,false);
    this._Option_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_23:any = 'en';
    this._Option_34_3.check_value(currVal_23,throwOnChange,false);
    this._Option_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    if (this._Item_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    this._ItemContent_39_5.detectChangesInternal(this,this._el_39,throwOnChange);
    this._Label_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Select_44_4.detectChangesInternal(this,this._el_44,throwOnChange);
    const currVal_30:any = this.context.model.source;
    this._NgModel_44_6.check_model(currVal_30,throwOnChange,false);
    this._NgModel_44_6.detectChangesInternal(this,this._el_44,throwOnChange);
    this._NgControlStatus_44_8.detectChangesInternal(this,this._el_44,throwOnChange);
    const currVal_37:any = 'brl';
    this._Option_46_3.check_value(currVal_37,throwOnChange,false);
    this._Option_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_39:any = 'eur';
    this._Option_49_3.check_value(currVal_39,throwOnChange,false);
    this._Option_49_3.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_41:any = 'usa';
    this._Option_52_3.check_value(currVal_41,throwOnChange,false);
    this._Option_52_3.detectChangesInternal(this,this._el_52,throwOnChange);
    this._Row_60_3.detectChangesInternal(this,this._el_60,throwOnChange);
    this._Col_62_3.detectChangesInternal(this,this._el_62,throwOnChange);
    this._List_64_3.detectChangesInternal(this,this._el_64,throwOnChange);
    if (this._Item_66_4.detectChangesInternal(this,this._el_66,throwOnChange)) { this._appEl_66.componentView.markAsCheckOnce(); }
    this._ItemContent_66_5.detectChangesInternal(this,this._el_66,throwOnChange);
    const currVal_44:any = '';
    this._Button_68_4.check_block(currVal_44,throwOnChange,false);
    if (this._Button_68_4.detectChangesInternal(this,this._el_68,throwOnChange)) { this._appEl_68.componentView.markAsCheckOnce(); }
    const currVal_45:any = 'ios-checkmark-circle';
    this._Icon_70_3.check_name(currVal_45,throwOnChange,false);
    this._Icon_70_3.detectChangesInternal(this,this._el_70,throwOnChange);
    const currVal_49:any = '';
    this._Button_73_4.check_block(currVal_49,throwOnChange,false);
    const currVal_50:any = 'danger';
    this._Button_73_4.check_color(currVal_50,throwOnChange,false);
    if (this._Button_73_4.detectChangesInternal(this,this._el_73,throwOnChange)) { this._appEl_73.componentView.markAsCheckOnce(); }
    const currVal_51:any = 'return-left';
    this._Icon_75_3.check_name(currVal_51,throwOnChange,false);
    this._Icon_75_3.detectChangesInternal(this,this._el_75,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Option_29_0.dirty) {
        this._query_Option_29_0.reset([
          this._Option_31_3.context,
          this._Option_34_3.context
        ]
        );
        this._Select_29_4.context.options = this._query_Option_29_0;
        this._query_Option_29_0.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Option_44_0.dirty) {
        this._query_Option_44_0.reset([
          this._Option_46_3.context,
          this._Option_49_3.context,
          this._Option_52_3.context
        ]
        );
        this._Select_44_4.context.options = this._query_Option_44_0;
        this._query_Option_44_0.notifyOnChanges();
      }
      if (this._query_Button_39_1.dirty) {
        this._query_Button_39_1.reset(([] as any[]));
        this._Item_39_4.context._buttons = this._query_Button_39_1;
        this._query_Button_39_1.notifyOnChanges();
      }
      if (this._query_Icon_39_2.dirty) {
        this._query_Icon_39_2.reset(([] as any[]));
        this._Item_39_4.context._icons = this._query_Icon_39_2;
        this._query_Icon_39_2.notifyOnChanges();
      }
      if (this._query_Button_66_1.dirty) {
        this._query_Button_66_1.reset([
          this._Button_68_4.context,
          this._Button_73_4.context
        ]
        );
        this._Item_66_4.context._buttons = this._query_Button_66_1;
        this._query_Button_66_1.notifyOnChanges();
      }
      if (this._query_Icon_66_2.dirty) {
        this._query_Icon_66_2.reset(([] as any[]));
        this._Item_66_4.context._icons = this._query_Icon_66_2;
        this._query_Icon_66_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_29_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_44_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_39_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_68_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_73_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_66_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    valUnwrapper.reset();
    const currVal_9:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SETTINGS.LANG')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setText(this._text_27,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._Select_29_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_29,'select-disabled',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = this._NgControlStatus_29_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_29_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_29_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_29_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_29_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_29_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    valUnwrapper.reset();
    const currVal_22:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_1.transform('SETTINGS.LANGS.PT')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_22,currVal_22))) {
      this.renderer.setText(this._text_32,currVal_22);
      this._expr_22 = currVal_22;
    }
    valUnwrapper.reset();
    const currVal_24:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_2.transform('SETTINGS.LANGS.EN')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_24,currVal_24))) {
      this.renderer.setText(this._text_35,currVal_24);
      this._expr_24 = currVal_24;
    }
    valUnwrapper.reset();
    const currVal_25:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_3.transform('SETTINGS.SOURCE')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_25,currVal_25))) {
      this.renderer.setText(this._text_42,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_29:any = this._Select_44_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_44,'select-disabled',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_31:any = this._NgControlStatus_44_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_44,'ng-untouched',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_44_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_44,'ng-touched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_44_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_44,'ng-pristine',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_44_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_44,'ng-dirty',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_44_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_44,'ng-valid',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_44_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_44,'ng-invalid',currVal_36);
      this._expr_36 = currVal_36;
    }
    valUnwrapper.reset();
    const currVal_38:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_4.transform('SETTINGS.SOURCES.BRL')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_38,currVal_38))) {
      this.renderer.setText(this._text_47,currVal_38);
      this._expr_38 = currVal_38;
    }
    valUnwrapper.reset();
    const currVal_40:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_5.transform('SETTINGS.SOURCES.EUR')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_40,currVal_40))) {
      this.renderer.setText(this._text_50,currVal_40);
      this._expr_40 = currVal_40;
    }
    valUnwrapper.reset();
    const currVal_42:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_6.transform('SETTINGS.SOURCES.USA')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_42,currVal_42))) {
      this.renderer.setText(this._text_53,currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_46:any = this._Icon_70_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_70,'hide',currVal_46);
      this._expr_46 = currVal_46;
    }
    valUnwrapper.reset();
    const currVal_47:any = import4.interpolate(1,'\n            ',valUnwrapper.unwrap(this._pipe_translate_7.transform('SETTINGS.BUTTONS.SAVE')),'\n          ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_47,currVal_47))) {
      this.renderer.setText(this._text_71,currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_52:any = this._Icon_75_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_75,'hide',currVal_52);
      this._expr_52 = currVal_52;
    }
    valUnwrapper.reset();
    const currVal_53:any = import4.interpolate(1,'\n            ',valUnwrapper.unwrap(this._pipe_translate_8.transform('SETTINGS.BUTTONS.BACK')),'\n          ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_53,currVal_53))) {
      this.renderer.setText(this._text_76,currVal_53);
      this._expr_53 = currVal_53;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Select_29_4.context.ngOnDestroy();
    this._NgModel_29_6.context.ngOnDestroy();
    this._Select_44_4.context.ngOnDestroy();
    this._NgModel_44_6.context.ngOnDestroy();
    this._Icon_70_3.context.ngOnDestroy();
    this._Icon_75_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
    this._pipe_translate_1.ngOnDestroy();
    this._pipe_translate_2.ngOnDestroy();
    this._pipe_translate_3.ngOnDestroy();
    this._pipe_translate_4.ngOnDestroy();
    this._pipe_translate_5.ngOnDestroy();
    this._pipe_translate_6.ngOnDestroy();
    this._pipe_translate_7.ngOnDestroy();
    this._pipe_translate_8.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.model.lang = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_1($event:any):boolean {
    this._appEl_29.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_29_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_29_2($event:any):boolean {
    this._appEl_29.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_29_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.model.source = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_44_1($event:any):boolean {
    this._appEl_44.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_44_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_44_2($event:any):boolean {
    this._appEl_44.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_44_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_68_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateSettings()) !== false);
    return (true && pd_0);
  }
  private _handle_click_73_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goHome()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PageSettings0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PageSettings> {
  if ((renderType_PageSettings === (null as any))) { (renderType_PageSettings = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_PageSettings,{})); }
  return new _View_PageSettings0(viewUtils,parentInjector,declarationEl);
}