/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/forms/src/directives';
import * as import3 from '@angular/forms/src/form_providers';
import * as import4 from '@angular/http/src/http_module';
import * as import5 from 'ng2-translate/index';
import * as import6 from '@angular/common/src/common_module';
import * as import7 from '@angular/core/src/application_module';
import * as import8 from '@angular/platform-browser/src/browser';
import * as import9 from 'ionic-angular/module';
import * as import10 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import11 from '@angular/http/src/backends/browser_xhr';
import * as import12 from '@angular/http/src/base_response_options';
import * as import13 from '@angular/http/src/backends/xhr_backend';
import * as import14 from '@angular/http/src/base_request_options';
import * as import15 from '@angular/common/src/localization';
import * as import16 from '../providers/ga';
import * as import17 from '../providers/error';
import * as import18 from 'ionic-angular/components/app/app';
import * as import19 from '@angular/core/src/application_init';
import * as import20 from '@angular/core/src/testability/testability';
import * as import21 from '@angular/core/src/application_ref';
import * as import22 from '@angular/core/src/linker/compiler';
import * as import23 from 'ionic-angular/gestures/gesture-config';
import * as import24 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import25 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import26 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import27 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import28 from '@angular/core/src/linker/view_utils';
import * as import29 from '@angular/platform-browser/src/browser/title';
import * as import30 from '@angular/forms/src/form_builder';
import * as import31 from 'ng2-translate/src/translate.service';
import * as import32 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import33 from 'ionic-angular/components/alert/alert';
import * as import34 from 'ionic-angular/util/events';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/util/haptic';
import * as import37 from 'ionic-angular/gestures/gesture-controller';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from 'ionic-angular/components/loading/loading';
import * as import40 from '@angular/common/src/location/location';
import * as import41 from 'ionic-angular/components/menu/menu-controller';
import * as import42 from 'ionic-angular/components/modal/modal';
import * as import43 from 'ionic-angular/components/picker/picker';
import * as import44 from 'ionic-angular/components/popover/popover';
import * as import45 from 'ionic-angular/components/tap-click/tap-click';
import * as import46 from 'ionic-angular/components/toast/toast';
import * as import47 from 'ionic-angular/translation/translate';
import * as import48 from 'ionic-angular/transitions/transition-controller';
import * as import49 from 'ionic-cache/src/cache.service';
import * as import50 from '../db/component';
import * as import51 from '../providers/size';
import * as import52 from '../providers/options';
import * as import53 from '../providers/page';
import * as import54 from '@angular/core/src/di/injector';
import * as import55 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import56 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import57 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import58 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import59 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import60 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import61 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import62 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import63 from './app.component.ngfactory';
import * as import64 from '../pages/pageHome/pageHome.ngfactory';
import * as import65 from '../pages/pageSizes/pageSizes.ngfactory';
import * as import66 from '../pages/pageSizeView/pageSizeView.ngfactory';
import * as import67 from '../pages/pageSizeForm/pageSizeForm.ngfactory';
import * as import68 from '../pages/pageSearch/pageSearch.ngfactory';
import * as import69 from '../pages/pageAbout/pageAbout.ngfactory';
import * as import70 from '../pages/pageSettings/pageSettings.ngfactory';
import * as import71 from '@angular/core/src/application_tokens';
import * as import72 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import73 from '@angular/platform-browser/src/dom/events/key_events';
import * as import74 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import75 from '@angular/core/src/zone/ng_zone';
import * as import76 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import77 from './app.component';
import * as import78 from '@angular/common/src/location/platform_location';
import * as import79 from '@angular/common/src/location/location_strategy';
import * as import80 from 'ionic-angular/navigation/url-serializer';
import * as import81 from 'ionic-angular/navigation/deep-linker';
import * as import82 from 'ionic-angular/platform/query-params';
import * as import83 from 'ionic-angular/platform/platform-registry';
import * as import84 from 'ionic-angular/platform/platform';
import * as import85 from 'ionic-angular/config/config';
import * as import86 from 'ionic-angular/config/mode-registry';
import * as import87 from 'ionic-angular/transitions/transition-registry';
import * as import88 from '@angular/core/src/console';
import * as import89 from '@angular/http/src/interfaces';
import * as import90 from '@angular/http/src/http';
import * as import91 from '@angular/core/src/i18n/tokens';
import * as import92 from '@angular/core/src/error_handler';
import * as import93 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import94 from '@angular/platform-browser/src/dom/animation_driver';
import * as import95 from '@angular/core/src/render/api';
import * as import96 from '@angular/core/src/security';
import * as import97 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import98 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import99 from 'ionic-angular/components/app/app-root';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _InternalFormsSharedModule_0:import2.InternalFormsSharedModule;
  _FormsModule_1:import3.FormsModule;
  _HttpModule_2:import4.HttpModule;
  _TranslateModule_3:import5.TranslateModule;
  _CommonModule_4:import6.CommonModule;
  _ApplicationModule_5:import7.ApplicationModule;
  _BrowserModule_6:import8.BrowserModule;
  _ReactiveFormsModule_7:import3.ReactiveFormsModule;
  _IonicModule_8:import9.IonicModule;
  _AppModule_9:import1.AppModule;
  __RadioControlRegistry_10:import10.RadioControlRegistry;
  __BrowserXhr_11:import11.BrowserXhr;
  __ResponseOptions_12:import12.BaseResponseOptions;
  __XSRFStrategy_13:any;
  __XHRBackend_14:import13.XHRBackend;
  __RequestOptions_15:import14.BaseRequestOptions;
  __Http_16:any;
  __LOCALE_ID_17:any;
  __NgLocalization_18:import15.NgLocaleLocalization;
  _GoogleAnalyticsProvider_19:import16.GoogleAnalyticsProvider;
  _ErrorHandler_20:import17.AppErrorHandler;
  _ConfigToken_21:any;
  _UrlToken_22:any;
  _QueryParams_23:any;
  _PlatformConfigToken_24:any;
  _UserAgentToken_25:any;
  _NavigatorPlatformToken_26:any;
  _DocumentDirToken_27:any;
  _DocLangToken_28:any;
  _Platform_29:any;
  _Config_30:any;
  _App_31:import18.App;
  _APP_INITIALIZER_32:any[];
  _ApplicationInitStatus_33:import19.ApplicationInitStatus;
  _Testability_34:import20.Testability;
  _ApplicationRef__35:import21.ApplicationRef_;
  __ApplicationRef_36:any;
  __Compiler_37:import22.Compiler;
  __APP_ID_38:any;
  __DOCUMENT_39:any;
  __HAMMER_GESTURE_CONFIG_40:import23.IonicGestureConfig;
  __EVENT_MANAGER_PLUGINS_41:any[];
  __EventManager_42:import24.EventManager;
  __DomSharedStylesHost_43:import25.DomSharedStylesHost;
  __AnimationDriver_44:any;
  __DomRootRenderer_45:import26.DomRootRenderer_;
  __RootRenderer_46:any;
  __DomSanitizer_47:import27.DomSanitizerImpl;
  __Sanitizer_48:any;
  __ViewUtils_49:import28.ViewUtils;
  __IterableDiffers_50:any;
  __KeyValueDiffers_51:any;
  __SharedStylesHost_52:any;
  __Title_53:import29.Title;
  __FormBuilder_54:import30.FormBuilder;
  __TranslateLoader_55:any;
  __TranslateService_56:import31.TranslateService;
  __AppRootToken_57:any;
  __DeepLinkConfigToken_58:any;
  __ActionSheetController_59:import32.ActionSheetController;
  __AlertController_60:import33.AlertController;
  __Events_61:import34.Events;
  __Form_62:import35.Form;
  __Haptic_63:import36.Haptic;
  __GestureController_64:import37.GestureController;
  __Keyboard_65:import38.Keyboard;
  __LoadingController_66:import39.LoadingController;
  __LocationStrategy_67:any;
  __Location_68:import40.Location;
  __MenuController_69:import41.MenuController;
  __ModalController_70:import42.ModalController;
  __PickerController_71:import43.PickerController;
  __PopoverController_72:import44.PopoverController;
  __TapClick_73:import45.TapClick;
  __ToastController_74:import46.ToastController;
  __Translate_75:import47.Translate;
  __TransitionController_76:import48.TransitionController;
  __UrlSerializer_77:any;
  __DeepLinker_78:any;
  __CacheService_79:import49.CacheService;
  __WhatsSizeDatabase_80:import50.WhatsSizeDatabase;
  __SizeProvider_81:import51.SizeProvider;
  __SizeOptionsProvider_82:import52.SizeOptionsProvider;
  __PageProvider_83:import53.PageProvider;
  constructor(parent:import54.Injector) {
    super(parent,[
      import55.ActionSheetCmpNgFactory,
      import56.AlertCmpNgFactory,
      import57.IonicAppNgFactory,
      import58.LoadingCmpNgFactory,
      import59.ModalCmpNgFactory,
      import60.PickerCmpNgFactory,
      import61.PopoverCmpNgFactory,
      import62.ToastCmpNgFactory,
      import63.WhatsSizeAppNgFactory,
      import63.WhatsSizeAppNgFactory,
      import64.PageHomeNgFactory,
      import65.PageSizesNgFactory,
      import66.PageSizeViewNgFactory,
      import67.PageSizeFormNgFactory,
      import68.PageSearchNgFactory,
      import69.PageAboutNgFactory,
      import70.PageSettingsNgFactory,
      import57.IonicAppNgFactory
    ]
    ,[import57.IonicAppNgFactory]);
  }
  get _RadioControlRegistry_10():import10.RadioControlRegistry {
    if ((this.__RadioControlRegistry_10 == (null as any))) { (this.__RadioControlRegistry_10 = new import10.RadioControlRegistry()); }
    return this.__RadioControlRegistry_10;
  }
  get _BrowserXhr_11():import11.BrowserXhr {
    if ((this.__BrowserXhr_11 == (null as any))) { (this.__BrowserXhr_11 = new import11.BrowserXhr()); }
    return this.__BrowserXhr_11;
  }
  get _ResponseOptions_12():import12.BaseResponseOptions {
    if ((this.__ResponseOptions_12 == (null as any))) { (this.__ResponseOptions_12 = new import12.BaseResponseOptions()); }
    return this.__ResponseOptions_12;
  }
  get _XSRFStrategy_13():any {
    if ((this.__XSRFStrategy_13 == (null as any))) { (this.__XSRFStrategy_13 = import4._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_13;
  }
  get _XHRBackend_14():import13.XHRBackend {
    if ((this.__XHRBackend_14 == (null as any))) { (this.__XHRBackend_14 = new import13.XHRBackend(this._BrowserXhr_11,this._ResponseOptions_12,this._XSRFStrategy_13)); }
    return this.__XHRBackend_14;
  }
  get _RequestOptions_15():import14.BaseRequestOptions {
    if ((this.__RequestOptions_15 == (null as any))) { (this.__RequestOptions_15 = new import14.BaseRequestOptions()); }
    return this.__RequestOptions_15;
  }
  get _Http_16():any {
    if ((this.__Http_16 == (null as any))) { (this.__Http_16 = import4.httpFactory(this._XHRBackend_14,this._RequestOptions_15)); }
    return this.__Http_16;
  }
  get _LOCALE_ID_17():any {
    if ((this.__LOCALE_ID_17 == (null as any))) { (this.__LOCALE_ID_17 = 'en-US'); }
    return this.__LOCALE_ID_17;
  }
  get _NgLocalization_18():import15.NgLocaleLocalization {
    if ((this.__NgLocalization_18 == (null as any))) { (this.__NgLocalization_18 = new import15.NgLocaleLocalization(this._LOCALE_ID_17)); }
    return this.__NgLocalization_18;
  }
  get _ApplicationRef_36():any {
    if ((this.__ApplicationRef_36 == (null as any))) { (this.__ApplicationRef_36 = this._ApplicationRef__35); }
    return this.__ApplicationRef_36;
  }
  get _Compiler_37():import22.Compiler {
    if ((this.__Compiler_37 == (null as any))) { (this.__Compiler_37 = new import22.Compiler()); }
    return this.__Compiler_37;
  }
  get _APP_ID_38():any {
    if ((this.__APP_ID_38 == (null as any))) { (this.__APP_ID_38 = import71._appIdRandomProviderFactory()); }
    return this.__APP_ID_38;
  }
  get _DOCUMENT_39():any {
    if ((this.__DOCUMENT_39 == (null as any))) { (this.__DOCUMENT_39 = import8._document()); }
    return this.__DOCUMENT_39;
  }
  get _HAMMER_GESTURE_CONFIG_40():import23.IonicGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_40 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_40 = new import23.IonicGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_40;
  }
  get _EVENT_MANAGER_PLUGINS_41():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_41 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_41 = [
      new import72.DomEventsPlugin(),
      new import73.KeyEventsPlugin(),
      new import74.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_40)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_41;
  }
  get _EventManager_42():import24.EventManager {
    if ((this.__EventManager_42 == (null as any))) { (this.__EventManager_42 = new import24.EventManager(this._EVENT_MANAGER_PLUGINS_41,this.parent.get(import75.NgZone))); }
    return this.__EventManager_42;
  }
  get _DomSharedStylesHost_43():import25.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_43 == (null as any))) { (this.__DomSharedStylesHost_43 = new import25.DomSharedStylesHost(this._DOCUMENT_39)); }
    return this.__DomSharedStylesHost_43;
  }
  get _AnimationDriver_44():any {
    if ((this.__AnimationDriver_44 == (null as any))) { (this.__AnimationDriver_44 = import8._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_44;
  }
  get _DomRootRenderer_45():import26.DomRootRenderer_ {
    if ((this.__DomRootRenderer_45 == (null as any))) { (this.__DomRootRenderer_45 = new import26.DomRootRenderer_(this._DOCUMENT_39,this._EventManager_42,this._DomSharedStylesHost_43,this._AnimationDriver_44)); }
    return this.__DomRootRenderer_45;
  }
  get _RootRenderer_46():any {
    if ((this.__RootRenderer_46 == (null as any))) { (this.__RootRenderer_46 = import76._createConditionalRootRenderer(this._DomRootRenderer_45,this.parent.get(import76.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_46;
  }
  get _DomSanitizer_47():import27.DomSanitizerImpl {
    if ((this.__DomSanitizer_47 == (null as any))) { (this.__DomSanitizer_47 = new import27.DomSanitizerImpl()); }
    return this.__DomSanitizer_47;
  }
  get _Sanitizer_48():any {
    if ((this.__Sanitizer_48 == (null as any))) { (this.__Sanitizer_48 = this._DomSanitizer_47); }
    return this.__Sanitizer_48;
  }
  get _ViewUtils_49():import28.ViewUtils {
    if ((this.__ViewUtils_49 == (null as any))) { (this.__ViewUtils_49 = new import28.ViewUtils(this._RootRenderer_46,this._APP_ID_38,this._Sanitizer_48)); }
    return this.__ViewUtils_49;
  }
  get _IterableDiffers_50():any {
    if ((this.__IterableDiffers_50 == (null as any))) { (this.__IterableDiffers_50 = import7._iterableDiffersFactory()); }
    return this.__IterableDiffers_50;
  }
  get _KeyValueDiffers_51():any {
    if ((this.__KeyValueDiffers_51 == (null as any))) { (this.__KeyValueDiffers_51 = import7._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_51;
  }
  get _SharedStylesHost_52():any {
    if ((this.__SharedStylesHost_52 == (null as any))) { (this.__SharedStylesHost_52 = this._DomSharedStylesHost_43); }
    return this.__SharedStylesHost_52;
  }
  get _Title_53():import29.Title {
    if ((this.__Title_53 == (null as any))) { (this.__Title_53 = new import29.Title()); }
    return this.__Title_53;
  }
  get _FormBuilder_54():import30.FormBuilder {
    if ((this.__FormBuilder_54 == (null as any))) { (this.__FormBuilder_54 = new import30.FormBuilder()); }
    return this.__FormBuilder_54;
  }
  get _TranslateLoader_55():any {
    if ((this.__TranslateLoader_55 == (null as any))) { (this.__TranslateLoader_55 = import1.createTranslateLoader(this._Http_16)); }
    return this.__TranslateLoader_55;
  }
  get _TranslateService_56():import31.TranslateService {
    if ((this.__TranslateService_56 == (null as any))) { (this.__TranslateService_56 = new import31.TranslateService(this._TranslateLoader_55,this.parent.get(import31.MissingTranslationHandler,(null as any)))); }
    return this.__TranslateService_56;
  }
  get _AppRootToken_57():any {
    if ((this.__AppRootToken_57 == (null as any))) { (this.__AppRootToken_57 = import77.WhatsSizeApp); }
    return this.__AppRootToken_57;
  }
  get _DeepLinkConfigToken_58():any {
    if ((this.__DeepLinkConfigToken_58 == (null as any))) { (this.__DeepLinkConfigToken_58 = (null as any)); }
    return this.__DeepLinkConfigToken_58;
  }
  get _ActionSheetController_59():import32.ActionSheetController {
    if ((this.__ActionSheetController_59 == (null as any))) { (this.__ActionSheetController_59 = new import32.ActionSheetController(this._App_31)); }
    return this.__ActionSheetController_59;
  }
  get _AlertController_60():import33.AlertController {
    if ((this.__AlertController_60 == (null as any))) { (this.__AlertController_60 = new import33.AlertController(this._App_31)); }
    return this.__AlertController_60;
  }
  get _Events_61():import34.Events {
    if ((this.__Events_61 == (null as any))) { (this.__Events_61 = new import34.Events()); }
    return this.__Events_61;
  }
  get _Form_62():import35.Form {
    if ((this.__Form_62 == (null as any))) { (this.__Form_62 = new import35.Form()); }
    return this.__Form_62;
  }
  get _Haptic_63():import36.Haptic {
    if ((this.__Haptic_63 == (null as any))) { (this.__Haptic_63 = new import36.Haptic(this._Platform_29)); }
    return this.__Haptic_63;
  }
  get _GestureController_64():import37.GestureController {
    if ((this.__GestureController_64 == (null as any))) { (this.__GestureController_64 = new import37.GestureController(this._App_31)); }
    return this.__GestureController_64;
  }
  get _Keyboard_65():import38.Keyboard {
    if ((this.__Keyboard_65 == (null as any))) { (this.__Keyboard_65 = new import38.Keyboard(this._Config_30,this._Form_62,this.parent.get(import75.NgZone))); }
    return this.__Keyboard_65;
  }
  get _LoadingController_66():import39.LoadingController {
    if ((this.__LoadingController_66 == (null as any))) { (this.__LoadingController_66 = new import39.LoadingController(this._App_31)); }
    return this.__LoadingController_66;
  }
  get _LocationStrategy_67():any {
    if ((this.__LocationStrategy_67 == (null as any))) { (this.__LocationStrategy_67 = import9.provideLocationStrategy(this.parent.get(import78.PlatformLocation),this.parent.get(import79.APP_BASE_HREF,(null as any)),this._Config_30)); }
    return this.__LocationStrategy_67;
  }
  get _Location_68():import40.Location {
    if ((this.__Location_68 == (null as any))) { (this.__Location_68 = new import40.Location(this._LocationStrategy_67)); }
    return this.__Location_68;
  }
  get _MenuController_69():import41.MenuController {
    if ((this.__MenuController_69 == (null as any))) { (this.__MenuController_69 = new import41.MenuController()); }
    return this.__MenuController_69;
  }
  get _ModalController_70():import42.ModalController {
    if ((this.__ModalController_70 == (null as any))) { (this.__ModalController_70 = new import42.ModalController(this._App_31)); }
    return this.__ModalController_70;
  }
  get _PickerController_71():import43.PickerController {
    if ((this.__PickerController_71 == (null as any))) { (this.__PickerController_71 = new import43.PickerController(this._App_31)); }
    return this.__PickerController_71;
  }
  get _PopoverController_72():import44.PopoverController {
    if ((this.__PopoverController_72 == (null as any))) { (this.__PopoverController_72 = new import44.PopoverController(this._App_31)); }
    return this.__PopoverController_72;
  }
  get _TapClick_73():import45.TapClick {
    if ((this.__TapClick_73 == (null as any))) { (this.__TapClick_73 = new import45.TapClick(this._Config_30,this._App_31,this.parent.get(import75.NgZone))); }
    return this.__TapClick_73;
  }
  get _ToastController_74():import46.ToastController {
    if ((this.__ToastController_74 == (null as any))) { (this.__ToastController_74 = new import46.ToastController(this._App_31)); }
    return this.__ToastController_74;
  }
  get _Translate_75():import47.Translate {
    if ((this.__Translate_75 == (null as any))) { (this.__Translate_75 = new import47.Translate()); }
    return this.__Translate_75;
  }
  get _TransitionController_76():import48.TransitionController {
    if ((this.__TransitionController_76 == (null as any))) { (this.__TransitionController_76 = new import48.TransitionController(this._Config_30)); }
    return this.__TransitionController_76;
  }
  get _UrlSerializer_77():any {
    if ((this.__UrlSerializer_77 == (null as any))) { (this.__UrlSerializer_77 = import80.setupUrlSerializer(this._DeepLinkConfigToken_58)); }
    return this.__UrlSerializer_77;
  }
  get _DeepLinker_78():any {
    if ((this.__DeepLinker_78 == (null as any))) { (this.__DeepLinker_78 = import81.setupDeepLinker(this._App_31,this._UrlSerializer_77,this._Location_68)); }
    return this.__DeepLinker_78;
  }
  get _CacheService_79():import49.CacheService {
    if ((this.__CacheService_79 == (null as any))) { (this.__CacheService_79 = new import49.CacheService()); }
    return this.__CacheService_79;
  }
  get _WhatsSizeDatabase_80():import50.WhatsSizeDatabase {
    if ((this.__WhatsSizeDatabase_80 == (null as any))) { (this.__WhatsSizeDatabase_80 = new import50.WhatsSizeDatabase()); }
    return this.__WhatsSizeDatabase_80;
  }
  get _SizeProvider_81():import51.SizeProvider {
    if ((this.__SizeProvider_81 == (null as any))) { (this.__SizeProvider_81 = new import51.SizeProvider()); }
    return this.__SizeProvider_81;
  }
  get _SizeOptionsProvider_82():import52.SizeOptionsProvider {
    if ((this.__SizeOptionsProvider_82 == (null as any))) { (this.__SizeOptionsProvider_82 = new import52.SizeOptionsProvider()); }
    return this.__SizeOptionsProvider_82;
  }
  get _PageProvider_83():import53.PageProvider {
    if ((this.__PageProvider_83 == (null as any))) { (this.__PageProvider_83 = new import53.PageProvider(this._App_31,this._TranslateService_56)); }
    return this.__PageProvider_83;
  }
  createInternal():import1.AppModule {
    this._InternalFormsSharedModule_0 = new import2.InternalFormsSharedModule();
    this._FormsModule_1 = new import3.FormsModule();
    this._HttpModule_2 = new import4.HttpModule();
    this._TranslateModule_3 = new import5.TranslateModule();
    this._CommonModule_4 = new import6.CommonModule();
    this._ApplicationModule_5 = new import7.ApplicationModule();
    this._BrowserModule_6 = new import8.BrowserModule(this.parent.get(import8.BrowserModule,(null as any)));
    this._ReactiveFormsModule_7 = new import3.ReactiveFormsModule();
    this._IonicModule_8 = new import9.IonicModule();
    this._AppModule_9 = new import1.AppModule();
    this._GoogleAnalyticsProvider_19 = new import16.GoogleAnalyticsProvider();
    this._ErrorHandler_20 = new import17.AppErrorHandler(this._GoogleAnalyticsProvider_19);
    this._ConfigToken_21 = (null as any);
    this._UrlToken_22 = import9.provideLocationHref();
    this._QueryParams_23 = import82.setupQueryParams(this._UrlToken_22);
    this._PlatformConfigToken_24 = import83.providePlatformConfigs();
    this._UserAgentToken_25 = import9.provideUserAgent();
    this._NavigatorPlatformToken_26 = import9.provideNavigatorPlatform();
    this._DocumentDirToken_27 = import9.provideDocumentDirection();
    this._DocLangToken_28 = import9.provideDocumentLang();
    this._Platform_29 = import84.setupPlatform(this._PlatformConfigToken_24,this._QueryParams_23,this._UserAgentToken_25,this._NavigatorPlatformToken_26,this._DocumentDirToken_27,this._DocLangToken_28,this.parent.get(import75.NgZone));
    this._Config_30 = import85.setupConfig(this._ConfigToken_21,this._QueryParams_23,this._Platform_29);
    this._App_31 = new import18.App(this._Config_30,this._Platform_29);
    this._APP_INITIALIZER_32 = [
      import86.registerModeConfigs(this._Config_30),
      import87.registerTransitions(this._Config_30),
      import34.setupProvideEvents(this._Platform_29),
      import45.setupTapClick(this._Config_30,this._App_31,this.parent.get(import75.NgZone))
    ]
    ;
    this._ApplicationInitStatus_33 = new import19.ApplicationInitStatus(this._APP_INITIALIZER_32);
    this._Testability_34 = new import20.Testability(this.parent.get(import75.NgZone));
    this._ApplicationRef__35 = new import21.ApplicationRef_(this.parent.get(import75.NgZone),this.parent.get(import88.Console),this,this._ErrorHandler_20,this,this._ApplicationInitStatus_33,this.parent.get(import20.TestabilityRegistry,(null as any)),this._Testability_34);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_0; }
    if ((token === import3.FormsModule)) { return this._FormsModule_1; }
    if ((token === import4.HttpModule)) { return this._HttpModule_2; }
    if ((token === import5.TranslateModule)) { return this._TranslateModule_3; }
    if ((token === import6.CommonModule)) { return this._CommonModule_4; }
    if ((token === import7.ApplicationModule)) { return this._ApplicationModule_5; }
    if ((token === import8.BrowserModule)) { return this._BrowserModule_6; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import9.IonicModule)) { return this._IonicModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import10.RadioControlRegistry)) { return this._RadioControlRegistry_10; }
    if ((token === import11.BrowserXhr)) { return this._BrowserXhr_11; }
    if ((token === import12.ResponseOptions)) { return this._ResponseOptions_12; }
    if ((token === import89.XSRFStrategy)) { return this._XSRFStrategy_13; }
    if ((token === import13.XHRBackend)) { return this._XHRBackend_14; }
    if ((token === import14.RequestOptions)) { return this._RequestOptions_15; }
    if ((token === import90.Http)) { return this._Http_16; }
    if ((token === import91.LOCALE_ID)) { return this._LOCALE_ID_17; }
    if ((token === import15.NgLocalization)) { return this._NgLocalization_18; }
    if ((token === import16.GoogleAnalyticsProvider)) { return this._GoogleAnalyticsProvider_19; }
    if ((token === import92.ErrorHandler)) { return this._ErrorHandler_20; }
    if ((token === import85.ConfigToken)) { return this._ConfigToken_21; }
    if ((token === import82.UrlToken)) { return this._UrlToken_22; }
    if ((token === import82.QueryParams)) { return this._QueryParams_23; }
    if ((token === import83.PlatformConfigToken)) { return this._PlatformConfigToken_24; }
    if ((token === import84.UserAgentToken)) { return this._UserAgentToken_25; }
    if ((token === import84.NavigatorPlatformToken)) { return this._NavigatorPlatformToken_26; }
    if ((token === import84.DocumentDirToken)) { return this._DocumentDirToken_27; }
    if ((token === import84.DocLangToken)) { return this._DocLangToken_28; }
    if ((token === import84.Platform)) { return this._Platform_29; }
    if ((token === import85.Config)) { return this._Config_30; }
    if ((token === import18.App)) { return this._App_31; }
    if ((token === import19.APP_INITIALIZER)) { return this._APP_INITIALIZER_32; }
    if ((token === import19.ApplicationInitStatus)) { return this._ApplicationInitStatus_33; }
    if ((token === import20.Testability)) { return this._Testability_34; }
    if ((token === import21.ApplicationRef_)) { return this._ApplicationRef__35; }
    if ((token === import21.ApplicationRef)) { return this._ApplicationRef_36; }
    if ((token === import22.Compiler)) { return this._Compiler_37; }
    if ((token === import71.APP_ID)) { return this._APP_ID_38; }
    if ((token === import93.DOCUMENT)) { return this._DOCUMENT_39; }
    if ((token === import74.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_40; }
    if ((token === import24.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_41; }
    if ((token === import24.EventManager)) { return this._EventManager_42; }
    if ((token === import25.DomSharedStylesHost)) { return this._DomSharedStylesHost_43; }
    if ((token === import94.AnimationDriver)) { return this._AnimationDriver_44; }
    if ((token === import26.DomRootRenderer)) { return this._DomRootRenderer_45; }
    if ((token === import95.RootRenderer)) { return this._RootRenderer_46; }
    if ((token === import27.DomSanitizer)) { return this._DomSanitizer_47; }
    if ((token === import96.Sanitizer)) { return this._Sanitizer_48; }
    if ((token === import28.ViewUtils)) { return this._ViewUtils_49; }
    if ((token === import97.IterableDiffers)) { return this._IterableDiffers_50; }
    if ((token === import98.KeyValueDiffers)) { return this._KeyValueDiffers_51; }
    if ((token === import25.SharedStylesHost)) { return this._SharedStylesHost_52; }
    if ((token === import29.Title)) { return this._Title_53; }
    if ((token === import30.FormBuilder)) { return this._FormBuilder_54; }
    if ((token === import31.TranslateLoader)) { return this._TranslateLoader_55; }
    if ((token === import31.TranslateService)) { return this._TranslateService_56; }
    if ((token === import99.AppRootToken)) { return this._AppRootToken_57; }
    if ((token === import80.DeepLinkConfigToken)) { return this._DeepLinkConfigToken_58; }
    if ((token === import32.ActionSheetController)) { return this._ActionSheetController_59; }
    if ((token === import33.AlertController)) { return this._AlertController_60; }
    if ((token === import34.Events)) { return this._Events_61; }
    if ((token === import35.Form)) { return this._Form_62; }
    if ((token === import36.Haptic)) { return this._Haptic_63; }
    if ((token === import37.GestureController)) { return this._GestureController_64; }
    if ((token === import38.Keyboard)) { return this._Keyboard_65; }
    if ((token === import39.LoadingController)) { return this._LoadingController_66; }
    if ((token === import79.LocationStrategy)) { return this._LocationStrategy_67; }
    if ((token === import40.Location)) { return this._Location_68; }
    if ((token === import41.MenuController)) { return this._MenuController_69; }
    if ((token === import42.ModalController)) { return this._ModalController_70; }
    if ((token === import43.PickerController)) { return this._PickerController_71; }
    if ((token === import44.PopoverController)) { return this._PopoverController_72; }
    if ((token === import45.TapClick)) { return this._TapClick_73; }
    if ((token === import46.ToastController)) { return this._ToastController_74; }
    if ((token === import47.Translate)) { return this._Translate_75; }
    if ((token === import48.TransitionController)) { return this._TransitionController_76; }
    if ((token === import80.UrlSerializer)) { return this._UrlSerializer_77; }
    if ((token === import81.DeepLinker)) { return this._DeepLinker_78; }
    if ((token === import49.CacheService)) { return this._CacheService_79; }
    if ((token === import50.WhatsSizeDatabase)) { return this._WhatsSizeDatabase_80; }
    if ((token === import51.SizeProvider)) { return this._SizeProvider_81; }
    if ((token === import52.SizeOptionsProvider)) { return this._SizeOptionsProvider_82; }
    if ((token === import53.PageProvider)) { return this._PageProvider_83; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__35.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);