/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './sizeView';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ng2-translate/src/translate.service';
import * as import12 from '../../../db/component';
import * as import13 from '../../../providers/size';
import * as import14 from '../../../providers/page';
import * as import15 from '../../../providers/ga';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '../../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import22 from '../../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from '../../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import25 from '../../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import26 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import27 from 'ng2-translate/src/translate.pipe';
import * as import28 from 'ionic-angular/util/form';
import * as import29 from 'ionic-angular/config/config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from 'ionic-angular/components/icon/icon';
import * as import33 from 'ionic-angular/components/button/button';
import * as import34 from 'ionic-angular/components/item/item';
import * as import35 from 'ionic-angular/components/grid/grid';
import * as import36 from '@angular/common/src/directives/ng_for';
import * as import37 from '../../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import38 from '../../../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import39 from 'ionic-angular/gestures/gesture-controller';
import * as import40 from 'ionic-angular/components/list/list-header';
import * as import41 from 'ionic-angular/components/list/list';
import * as import42 from '@angular/core/src/security';
export class Wrapper_SizeView {
  context:import0.SizeView;
  changed:boolean;
  /*private*/ _entity:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any,p7:any) {
    this.changed = false;
    this._entity = import1.UNINITIALIZED;
    this.context = new import0.SizeView(p0,p1,p2,p3,p4,p5,p6,p7);
  }
  check_entity(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._entity,currValue))) {
      this.changed = true;
      this.context.entity = currValue;
      this._entity = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SizeView_Host:import4.RenderComponentType = (null as any);
class _View_SizeView_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _SizeView_0_4:Wrapper_SizeView;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SizeView_Host0,renderType_SizeView_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('size-view',rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SizeView0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SizeView_0_4 = new Wrapper_SizeView(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.TranslateService),this.parentInjector.get(import12.WhatsSizeDatabase),this.parentInjector.get(import13.SizeProvider),this.parentInjector.get(import14.PageProvider),this.parentInjector.get(import15.GoogleAnalyticsProvider));
    this._appEl_0.initComponent(this._SizeView_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SizeView_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SizeView) && (0 === requestNodeIndex))) { return this._SizeView_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SizeView_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SizeView_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_SizeView_Host === (null as any))) { (renderType_SizeView_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SizeView_Host0(viewUtils,parentInjector,declarationEl);
}
export const SizeViewNgFactory:import17.ComponentFactory<import0.SizeView> = new import17.ComponentFactory<import0.SizeView>('size-view',viewFactory_SizeView_Host0,import0.SizeView);
const styles_SizeView:any[] = ([] as any[]);
var renderType_SizeView:import4.RenderComponentType = (null as any);
class _View_SizeView0 extends import3.AppView<import0.SizeView> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import5.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SizeView0,renderType_SizeView,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import5.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import19.TemplateRef_(this._appEl_2,viewFactory_SizeView1);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.model.isLoaded;
    this._NgIf_2_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_SizeView0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.SizeView> {
  if ((renderType_SizeView === (null as any))) { (renderType_SizeView = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,styles_SizeView,{})); }
  return new _View_SizeView0(viewUtils,parentInjector,declarationEl);
}
class _View_SizeView1 extends import3.AppView<any> {
  _el_0:any;
  _Grid_0_3:import21.Wrapper_Grid;
  _text_1:any;
  _el_2:any;
  _Row_2_3:import21.Wrapper_Row;
  _text_3:any;
  _el_4:any;
  _Col_4_3:import21.Wrapper_Col;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import5.AppElement;
  _Item_6_4:import22.Wrapper_Item;
  _ItemContent_6_5:import22.Wrapper_ItemContent;
  _query_Label_6_0:import23.QueryList<any>;
  _query_Button_6_1:import23.QueryList<any>;
  _query_Icon_6_2:import23.QueryList<any>;
  _text_7:any;
  _el_8:any;
  _Icon_8_3:import24.Wrapper_Icon;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import5.AppElement;
  _Button_15_4:import25.Wrapper_Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import24.Wrapper_Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _Row_24_3:import21.Wrapper_Row;
  _text_25:any;
  _el_26:any;
  _Col_26_3:import21.Wrapper_Col;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import5.AppElement;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import26.Wrapper_NgFor;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_8:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SizeView1,renderType_SizeView,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_0_3 = new import21.Wrapper_Grid();
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this._Row_2_3 = new import21.Wrapper_Row();
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_4,'width-100','');
    this._Col_4_3 = new import21.Wrapper_Col();
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','item item-block');
    this._appEl_6 = new import5.AppElement(6,4,this,this._el_6);
    var compView_6:any = import22.viewFactory_Item0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Item_6_4 = new import22.Wrapper_Item(this.parent.parentInjector.get(import28.Form),this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_6),this.renderer);
    this._ItemContent_6_5 = new import22.Wrapper_ItemContent();
    this._query_Label_6_0 = new import23.QueryList<any>();
    this._query_Button_6_1 = new import23.QueryList<any>();
    this._query_Icon_6_2 = new import23.QueryList<any>();
    this._appEl_6.initComponent(this._Item_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_8,'item-left','');
    this.renderer.setElementAttribute(this._el_8,'large','');
    this.renderer.setElementAttribute(this._el_8,'role','img');
    this._Icon_8_3 = new import24.Wrapper_Icon(this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_13,'item-right','');
    this._text_14 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'color','primary');
    this.renderer.setElementAttribute(this._el_15,'icon-left','');
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this.renderer.setElementAttribute(this._el_15,'item-right','');
    this.renderer.setElementAttribute(this._el_15,'outline','');
    this.renderer.setElementAttribute(this._el_15,'small','');
    this.renderer.setElementAttribute(this._el_15,'type','button');
    this._appEl_15 = new import5.AppElement(15,13,this,this._el_15);
    var compView_15:any = import25.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import25.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'name','open');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import24.Wrapper_Icon(this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'',(null as any));
      compView_15.create(this._Button_15_4.context,[([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._query_Label_6_0.reset(([] as any[]));
    this._Item_6_4.context.contentLabel = this._query_Label_6_0.first;
    compView_6.create(this._Item_6_4.context,[
      ([] as any[]).concat([this._el_8]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_7,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_20
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_13])
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','padding');
    this._Row_24_3 = new import21.Wrapper_Row();
    this._text_25 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_26,'width-100','');
    this._Col_26_3 = new import21.Wrapper_Col();
    this._text_27 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._appEl_28 = new import5.AppElement(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import19.TemplateRef_(this._appEl_28,viewFactory_SizeView2);
    this._NgFor_28_6 = new import26.Wrapper_NgFor(this._appEl_28.vcRef,this._TemplateRef_28_5,this.parent.parentInjector.get(import31.IterableDiffers),this.parent.ref);
    this._text_29 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._expr_8 = import1.UNINITIALIZED;
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import11.TranslateService),this.parent.ref);
    this._expr_9 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.Icon) && (8 === requestNodeIndex))) { return this._Icon_8_3.context; }
    if (((token === import32.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3.context; }
    if (((token === import33.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4.context; }
    if (((token === import34.Item) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_6_4.context; }
    if (((token === import34.ItemContent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemContent_6_5.context; }
    if (((token === import35.Col) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Col_4_3.context; }
    if (((token === import35.Row) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Row_2_3.context; }
    if (((token === import19.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import36.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6.context; }
    if (((token === import35.Col) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Col_26_3.context; }
    if (((token === import35.Row) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Row_24_3.context; }
    if (((token === import35.Grid) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Grid_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this._Grid_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Row_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Col_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    if (this._Item_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    this._ItemContent_6_5.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_0:any = this.parent.context.model.sizeTypeIcon;
    this._Icon_8_3.check_name(currVal_0,throwOnChange,false);
    this._Icon_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    const currVal_4:any = '';
    this._Button_15_4.check_small(currVal_4,throwOnChange,false);
    const currVal_5:any = '';
    this._Button_15_4.check_outline(currVal_5,throwOnChange,false);
    const currVal_6:any = 'primary';
    this._Button_15_4.check_color(currVal_6,throwOnChange,false);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    const currVal_7:any = 'open';
    this._Icon_17_3.check_name(currVal_7,throwOnChange,false);
    this._Icon_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    this._Row_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Col_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_10:any = this.parent.context.model.convertedSize;
    this._NgFor_28_6.check_ngForOf(currVal_10,throwOnChange,false);
    this._NgFor_28_6.detectChangesInternal(this,this._anchor_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_1.dirty) {
        this._query_Button_6_1.reset([this._Button_15_4.context]);
        this._Item_6_4.context._buttons = this._query_Button_6_1;
        this._query_Button_6_1.notifyOnChanges();
      }
      if (this._query_Icon_6_2.dirty) {
        this._query_Icon_6_2.reset([this._Icon_8_3.context]);
        this._Item_6_4.context._icons = this._query_Icon_6_2;
        this._query_Icon_6_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_6_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Icon_8_3.context._hidden;
    if (import2.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_8,'hide',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import2.interpolate(1,'',this.parent.context.model.entity.personName,'');
    if (import2.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_11,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_8:any = this._Icon_17_3.context._hidden;
    if (import2.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    valUnwrapper.reset();
    const currVal_9:any = import2.interpolate(1,'\n                ',valUnwrapper.unwrap(this._pipe_translate_0.transform('SIZEVIEW.BUTTONS.EDIT')),'\n              ');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setText(this._text_18,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_8_3.context.ngOnDestroy();
    this._Icon_17_3.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.editSize(this.parent.context.model.entity)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SizeView1(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_SizeView1(viewUtils,parentInjector,declarationEl);
}
class _View_SizeView2 extends import3.AppView<any> {
  _el_0:any;
  _List_0_3:import37.Wrapper_List;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import5.AppElement;
  _Item_2_4:import22.Wrapper_Item;
  _ListHeader_2_5:import38.Wrapper_ListHeader;
  _query_Label_2_0:import23.QueryList<any>;
  _query_Button_2_1:import23.QueryList<any>;
  _query_Icon_2_2:import23.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import5.AppElement;
  _Item_5_4:import22.Wrapper_Item;
  _ItemContent_5_5:import22.Wrapper_ItemContent;
  _query_Label_5_0:import23.QueryList<any>;
  _query_Button_5_1:import23.QueryList<any>;
  _query_Icon_5_2:import23.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Row_7_3:import21.Wrapper_Row;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import5.AppElement;
  _TemplateRef_9_5:any;
  _NgFor_9_6:import26.Wrapper_NgFor;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SizeView2,renderType_SizeView,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_0_3 = new import37.Wrapper_List(this.parent.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer,this.parent.parent.parentInjector.get(import39.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item');
    this._appEl_2 = new import5.AppElement(2,0,this,this._el_2);
    var compView_2:any = import22.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import22.Wrapper_Item(this.parent.parent.parentInjector.get(import28.Form),this.parent.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer);
    this._ListHeader_2_5 = new import38.Wrapper_ListHeader(this.parent.parent.parentInjector.get(import29.Config),this.renderer,new import30.ElementRef(this._el_2),(null as any));
    this._query_Label_2_0 = new import23.QueryList<any>();
    this._query_Button_2_1 = new import23.QueryList<any>();
    this._query_Icon_2_2 = new import23.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','item-size item item-block');
    this._appEl_5 = new import5.AppElement(5,0,this,this._el_5);
    var compView_5:any = import22.viewFactory_Item0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Item_5_4 = new import22.Wrapper_Item(this.parent.parent.parentInjector.get(import28.Form),this.parent.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_5),this.renderer);
    this._ItemContent_5_5 = new import22.Wrapper_ItemContent();
    this._query_Label_5_0 = new import23.QueryList<any>();
    this._query_Button_5_1 = new import23.QueryList<any>();
    this._query_Icon_5_2 = new import23.QueryList<any>();
    this._appEl_5.initComponent(this._Item_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_7_3 = new import21.Wrapper_Row();
    this._text_8 = this.renderer.createText(this._el_7,'\n                            ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import5.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import19.TemplateRef_(this._appEl_9,viewFactory_SizeView3);
    this._NgFor_9_6 = new import26.Wrapper_NgFor(this._appEl_9.vcRef,this._TemplateRef_9_5,this.parent.parent.parentInjector.get(import31.IterableDiffers),this.parent.parent.ref);
    this._text_10 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._query_Label_5_0.reset(([] as any[]));
    this._Item_5_4.context.contentLabel = this._query_Label_5_0.first;
    compView_5.create(this._Item_5_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_11
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import11.TranslateService),this.parent.parent.ref);
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4.context; }
    if (((token === import40.ListHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ListHeader_2_5.context; }
    if (((token === import19.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import36.NgFor) && (9 === requestNodeIndex))) { return this._NgFor_9_6.context; }
    if (((token === import35.Row) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Row_7_3.context; }
    if (((token === import34.Item) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Item_5_4.context; }
    if (((token === import34.ItemContent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ItemContent_5_5.context; }
    if (((token === import41.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ListHeader_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Item_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    this._ItemContent_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._Row_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_1:any = this.context.$implicit.value;
    this._NgFor_9_6.check_ngForOf(currVal_1,throwOnChange,false);
    this._NgFor_9_6.detectChangesInternal(this,this._anchor_9,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_Button_5_1.dirty) {
        this._query_Button_5_1.reset(([] as any[]));
        this._Item_5_4.context._buttons = this._query_Button_5_1;
        this._query_Button_5_1.notifyOnChanges();
      }
      if (this._query_Icon_5_2.dirty) {
        this._query_Icon_5_2.reset(([] as any[]));
        this._Item_5_4.context._icons = this._query_Icon_5_2;
        this._query_Icon_5_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_5_4.context.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = import2.interpolate(1,'\n                        ',valUnwrapper.unwrap(this._pipe_translate_0.transform(this.context.$implicit.key)),'\n                    ');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_translate_0.ngOnDestroy();
  }
}
function viewFactory_SizeView2(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_SizeView2(viewUtils,parentInjector,declarationEl);
}
class _View_SizeView3 extends import3.AppView<any> {
  _el_0:any;
  _Col_0_3:import21.Wrapper_Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import5.AppElement;
  _Item_2_4:import22.Wrapper_Item;
  _ItemContent_2_5:import22.Wrapper_ItemContent;
  _query_Label_2_0:import23.QueryList<any>;
  _query_Button_2_1:import23.QueryList<any>;
  _query_Icon_2_2:import23.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SizeView3,renderType_SizeView,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_0,'width-30','');
    this._Col_0_3 = new import21.Wrapper_Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import5.AppElement(2,0,this,this._el_2);
    var compView_2:any = import22.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import22.Wrapper_Item(this.parent.parent.parent.parentInjector.get(import28.Form),this.parent.parent.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import22.Wrapper_ItemContent();
    this._query_Label_2_0 = new import23.QueryList<any>();
    this._query_Button_2_1 = new import23.QueryList<any>();
    this._query_Icon_2_2 = new import23.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n                                    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','flag');
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this.renderer.setElementAttribute(this._el_4,'large','');
    this._text_5 = this.renderer.createText((null as any),'\n                                    ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h5',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n                                    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n                                ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_5,
        this._el_6,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Item_2_4.context; }
    if (((token === import34.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ItemContent_2_5.context; }
    if (((token === import35.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Col_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Col_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.flag;
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import2.interpolate(1,'',this.context.$implicit.text,'');
    if (import2.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import2.interpolate(1,'',this.context.$implicit.value,'');
    if (import2.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SizeView3(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_SizeView3(viewUtils,parentInjector,declarationEl);
}