/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pageHome';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ng2-translate/src/translate.service';
import * as import10 from '../../db/component';
import * as import11 from '../../providers/ga';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from '@angular/core/src/linker/template_ref';
import * as import34 from 'ionic-angular/components/icon/icon';
import * as import35 from 'ionic-angular/components/button/button';
import * as import36 from 'ionic-angular/components/menu/menu-toggle';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import39 from 'ionic-angular/components/navbar/navbar';
import * as import40 from '@angular/common/src/directives/ng_if';
import * as import41 from 'ionic-angular/components/content/content';
import * as import42 from '../../node_modules/ionic-angular/components/slides/slides.ngfactory';
import * as import43 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import44 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/badge/badge.ngfactory';
import * as import46 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import47 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import48 from 'ng2-translate/src/translate.pipe';
import * as import49 from 'ionic-angular/util/form';
import * as import50 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import51 from 'ionic-angular/components/badge/badge';
import * as import52 from 'ionic-angular/components/item/item';
import * as import53 from 'ionic-angular/components/grid/grid';
import * as import54 from 'ionic-angular/components/card/card';
import * as import55 from 'ionic-angular/components/slides/slides';
import * as import56 from '@angular/common/src/directives/ng_for';
import * as import57 from '../pageSizeView/components/sizeView.ngfactory';
import * as import58 from 'ionic-angular/navigation/nav-params';
import * as import59 from 'ionic-angular/components/alert/alert';
import * as import60 from '../../providers/size';
import * as import61 from '../../providers/page';
import * as import62 from '../pageSizeView/components/sizeView';
export class Wrapper_PageHome {
  context:import0.PageHome;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.PageHome(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PageHome_Host:import2.RenderComponentType = (null as any);
class _View_PageHome_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PageHome_0_4:Wrapper_PageHome;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageHome_Host0,renderType_PageHome_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-pageHome',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageHome0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageHome_0_4 = new Wrapper_PageHome(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.TranslateService),this.parentInjector.get(import10.WhatsSizeDatabase),this.parentInjector.get(import11.GoogleAnalyticsProvider));
    this._appEl_0.initComponent(this._PageHome_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PageHome_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PageHome) && (0 === requestNodeIndex))) { return this._PageHome_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PageHome_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PageHome_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PageHome_Host === (null as any))) { (renderType_PageHome_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PageHome_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageHomeNgFactory:import13.ComponentFactory<import0.PageHome> = new import13.ComponentFactory<import0.PageHome>('page-pageHome',viewFactory_PageHome_Host0,import0.PageHome);
const styles_PageHome:any[] = ([] as any[]);
var renderType_PageHome:import2.RenderComponentType = (null as any);
class _View_PageHome0 extends import1.AppView<import0.PageHome> {
  _viewQuery_homeSlider_0:import14.QueryList<any>;
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import17.Wrapper_Button;
  _MenuToggle_4_5:import18.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import19.Wrapper_ToolbarItem;
  _query_Button_4_0:import14.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import20.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import21.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import22.Wrapper_Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import23.Wrapper_NgIf;
  _text_17:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageHome0,renderType_PageHome,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_homeSlider_0 = new import14.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this.renderer.setElementAttribute(this._el_2,'id','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import17.Wrapper_Button('','',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import18.Wrapper_MenuToggle(this.parentInjector.get(import28.MenuController),new import25.ElementRef(this._el_4),this.parentInjector.get(import26.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import19.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import14.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import20.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import21.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import21.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Whats Size',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import22.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import22.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import3.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import33.TemplateRef_(this._appEl_16,viewFactory_PageHome1);
    this._NgIf_16_6 = new import23.Wrapper_NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._appEl_16,
        this._text_17
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import35.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import36.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import37.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import38.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import39.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import29.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import33.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import40.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import41.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_6_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_9:any = this.context.model.isLoaded;
    this._NgIf_16_6.check_ngIf(currVal_9,throwOnChange,false);
    this._NgIf_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._viewQuery_homeSlider_0.dirty) {
          this._viewQuery_homeSlider_0.reset([this._appEl_16.mapNestedViews(_View_PageHome1,(nestedView:_View_PageHome1):any => {
            return [nestedView._Slides_0_4.context];
        })]);
        this.context.slider = this._viewQuery_homeSlider_0.first;
      }
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PageHome0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PageHome> {
  if ((renderType_PageHome === (null as any))) { (renderType_PageHome = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_PageHome,{})); }
  return new _View_PageHome0(viewUtils,parentInjector,declarationEl);
}
class _View_PageHome1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Slides_0_4:import42.Wrapper_Slides;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Slide_2_4:import42.Wrapper_Slide;
  _text_3:any;
  _el_4:any;
  _Row_4_3:import43.Wrapper_Row;
  _text_5:any;
  _el_6:any;
  _Col_6_3:import43.Wrapper_Col;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _Item_8_4:import44.Wrapper_Item;
  _ItemContent_8_5:import44.Wrapper_ItemContent;
  _query_Label_8_0:import14.QueryList<any>;
  _query_Button_8_1:import14.QueryList<any>;
  _query_Icon_8_2:import14.QueryList<any>;
  _text_9:any;
  _el_10:any;
  _Icon_10_3:import20.Wrapper_Icon;
  _text_11:any;
  _el_12:any;
  _Badge_12_3:import45.Wrapper_Badge;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _Row_18_3:import43.Wrapper_Row;
  _text_19:any;
  _el_20:any;
  _Col_20_3:import43.Wrapper_Col;
  _text_21:any;
  _el_22:any;
  _Card_22_3:import46.Wrapper_Card;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _CardContent_26_3:import46.Wrapper_CardContent;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _Badge_30_3:import45.Wrapper_Badge;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import20.Wrapper_Icon;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _CardTitle_36_3:import46.Wrapper_CardTitle;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _TemplateRef_47_5:any;
  _NgFor_47_6:import47.Wrapper_NgFor;
  _text_48:any;
  /*private*/ _expr_2:any;
  _pipe_translate_0:import48.TranslatePipe;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  _pipe_translate_1:import48.TranslatePipe;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  _pipe_translate_2:import48.TranslatePipe;
  /*private*/ _expr_10:any;
  _pipe_translate_3:import48.TranslatePipe;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageHome1,renderType_PageHome,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-slides',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import42.viewFactory_Slides0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Slides_0_4 = new import42.Wrapper_Slides(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Slides_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import42.viewFactory_Slide0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Slide_2_4 = new import42.Wrapper_Slide(new import25.ElementRef(this._el_2),this._Slides_0_4.context);
    this._appEl_2.initComponent(this._Slide_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_4_3 = new import43.Wrapper_Row();
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_6,'width-100','');
    this._Col_6_3 = new import43.Wrapper_Col();
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','item item-block');
    this._appEl_8 = new import3.AppElement(8,6,this,this._el_8);
    var compView_8:any = import44.viewFactory_Item0(this.viewUtils,this.injector(8),this._appEl_8);
    this._Item_8_4 = new import44.Wrapper_Item(this.parent.parentInjector.get(import49.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_8),this.renderer);
    this._ItemContent_8_5 = new import44.Wrapper_ItemContent();
    this._query_Label_8_0 = new import14.QueryList<any>();
    this._query_Button_8_1 = new import14.QueryList<any>();
    this._query_Icon_8_2 = new import14.QueryList<any>();
    this._appEl_8.initComponent(this._Item_8_4.context,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_10,'item-left','');
    this.renderer.setElementAttribute(this._el_10,'name','md-contacts');
    this.renderer.setElementAttribute(this._el_10,'role','img');
    this._Icon_10_3 = new import20.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText((null as any),'',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_12,'item-right','');
    this._Badge_12_3 = new import45.Wrapper_Badge(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_8_0.reset(([] as any[]));
    this._Item_8_4.context.contentLabel = this._query_Label_8_0.first;
    compView_8.create(this._Item_8_4.context,[
      ([] as any[]).concat([this._el_10]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_9,
        this._text_11,
        this._text_14
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_12])
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_18_3 = new import43.Wrapper_Row();
    this._text_19 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_20,'width-100','');
    this._Col_20_3 = new import43.Wrapper_Col();
    this._text_21 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-card',(null as any));
    this._Card_22_3 = new import46.Wrapper_Card(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'img',(null as any));
    this.renderer.setElementAttribute(this._el_24,'src','assets/images/home.jpg');
    this._text_25 = this.renderer.createText(this._el_22,'\n\n            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_22,'ion-card-content',(null as any));
    this._CardContent_26_3 = new import46.Wrapper_CardContent();
    this._text_27 = this.renderer.createText(this._el_26,'\n              ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_30,'color','secondary');
    this.renderer.setElementAttribute(this._el_30,'item-right','');
    this._Badge_30_3 = new import45.Wrapper_Badge(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(this._el_30,'',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_32,'name','arrow-forward');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import20.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_32),this.renderer);
    this._text_33 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_28,'\n              ',(null as any));
    this._text_35 = this.renderer.createText(this._el_26,'\n              ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_26,'ion-card-title',(null as any));
    this._CardTitle_36_3 = new import46.Wrapper_CardTitle();
    this._text_37 = this.renderer.createText(this._el_36,'',(null as any));
    this._text_38 = this.renderer.createText(this._el_26,'\n              ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'',(null as any));
    this._text_41 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._text_43 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_2.create(this._Slide_2_4.context,[([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_17,
        this._el_18,
        this._text_45
      ]
    )],(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_47 = new import3.AppElement(47,0,this,this._anchor_47);
    this._TemplateRef_47_5 = new import33.TemplateRef_(this._appEl_47,viewFactory_PageHome2);
    this._NgFor_47_6 = new import47.Wrapper_NgFor(this._appEl_47.vcRef,this._TemplateRef_47_5,this.parent.parentInjector.get(import50.IterableDiffers),this.parent.ref);
    this._text_48 = this.renderer.createText((null as any),'\n  ',(null as any));
      compView_0.create(this._Slides_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_46,
        this._appEl_47,
        this._text_48
      ]
    )],(null as any));
    this._expr_2 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import48.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.parent.ref);
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._pipe_translate_1 = new import48.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.parent.ref);
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._pipe_translate_2 = new import48.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.parent.ref);
    this._expr_10 = import7.UNINITIALIZED;
    this._pipe_translate_3 = new import48.TranslatePipe(this.parentInjector.get(import9.TranslateService),this.parent.ref);
    this._expr_11 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._anchor_47,
      this._text_48
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Icon) && (10 === requestNodeIndex))) { return this._Icon_10_3.context; }
    if (((token === import51.Badge) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Badge_12_3.context; }
    if (((token === import52.Item) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_8_4.context; }
    if (((token === import52.ItemContent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_8_5.context; }
    if (((token === import53.Col) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Col_6_3.context; }
    if (((token === import53.Row) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Row_4_3.context; }
    if (((token === import34.Icon) && (32 === requestNodeIndex))) { return this._Icon_32_3.context; }
    if (((token === import51.Badge) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Badge_30_3.context; }
    if (((token === import54.CardTitle) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._CardTitle_36_3.context; }
    if (((token === import54.CardContent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._CardContent_26_3.context; }
    if (((token === import54.Card) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Card_22_3.context; }
    if (((token === import53.Col) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Col_20_3.context; }
    if (((token === import53.Row) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Row_18_3.context; }
    if (((token === import55.Slide) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Slide_2_4.context; }
    if (((token === import33.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import56.NgFor) && (47 === requestNodeIndex))) { return this._NgFor_47_6.context; }
    if (((token === import55.Slides) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Slides_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = this._Slides_0_4.context;
    this._Slides_0_4.check_options(currVal_0,throwOnChange,false);
    if (this._Slides_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (this._Slide_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._Row_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Col_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._Item_8_4.detectChangesInternal(this,this._el_8,throwOnChange)) { this._appEl_8.componentView.markAsCheckOnce(); }
    this._ItemContent_8_5.detectChangesInternal(this,this._el_8,throwOnChange);
    const currVal_1:any = 'md-contacts';
    this._Icon_10_3.check_name(currVal_1,throwOnChange,false);
    this._Icon_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    this._Badge_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this._Row_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._Col_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._Card_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    this._CardContent_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_6:any = 'secondary';
    this._Badge_30_3.check_color(currVal_6,throwOnChange,false);
    this._Badge_30_3.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_8:any = 'arrow-forward';
    this._Icon_32_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    this._CardTitle_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_12:any = this.parent.context.model.sizes;
    this._NgFor_47_6.check_ngForOf(currVal_12,throwOnChange,false);
    this._NgFor_47_6.detectChangesInternal(this,this._anchor_47,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_8_1.dirty) {
        this._query_Button_8_1.reset(([] as any[]));
        this._Item_8_4.context._buttons = this._query_Button_8_1;
        this._query_Button_8_1.notifyOnChanges();
      }
      if (this._query_Icon_8_2.dirty) {
        this._query_Icon_8_2.reset([this._Icon_10_3.context]);
        this._Item_8_4.context._icons = this._query_Icon_8_2;
        this._query_Icon_8_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_8_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Icon_10_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import4.interpolate(1,'\n            ',valUnwrapper.unwrap(this._pipe_translate_0.transform('HOME.TITLE')),'\n            ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_11,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = import4.interpolate(1,'',this.parent.context.model.sizesCount,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_13,currVal_5);
      this._expr_5 = currVal_5;
    }
    valUnwrapper.reset();
    const currVal_7:any = import4.interpolate(1,'\n                  ',valUnwrapper.unwrap(this._pipe_translate_1.transform('HOME.TOUCHMESSAGE')),'\n                  ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_7,currVal_7))) {
      this.renderer.setText(this._text_31,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_32_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_32,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    valUnwrapper.reset();
    const currVal_10:any = import4.interpolate(1,'\n                ',valUnwrapper.unwrap(this._pipe_translate_2.transform('HOME.CARDTITLE')),'\n              ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_10,currVal_10))) {
      this.renderer.setText(this._text_37,currVal_10);
      this._expr_10 = currVal_10;
    }
    valUnwrapper.reset();
    const currVal_11:any = import4.interpolate(1,'\n                ',valUnwrapper.unwrap(this._pipe_translate_3.transform('HOME.MESSAGE')),'\n              ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_11,currVal_11))) {
      this.renderer.setText(this._text_40,currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PageHome0>this.parent)._viewQuery_homeSlider_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_10_3.context.ngOnDestroy();
    this._Icon_32_3.context.ngOnDestroy();
    this._Slide_2_4.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
    this._pipe_translate_1.ngOnDestroy();
    this._pipe_translate_2.ngOnDestroy();
    this._pipe_translate_3.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.clickCount()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PageHome1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageHome1(viewUtils,parentInjector,declarationEl);
}
class _View_PageHome2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Slide_0_4:import42.Wrapper_Slide;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _SizeView_2_4:import57.Wrapper_SizeView;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageHome2,renderType_PageHome,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import42.viewFactory_Slide0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Slide_0_4 = new import42.Wrapper_Slide(new import25.ElementRef(this._el_0),(<_View_PageHome1>this.parent)._Slides_0_4.context);
    this._appEl_0.initComponent(this._Slide_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'size-view',(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import57.viewFactory_SizeView0(this.viewUtils,this.injector(2),this._appEl_2);
    this._SizeView_2_4 = new import57.Wrapper_SizeView(this.parent.parent.parentInjector.get(import8.NavController),this.parent.parent.parentInjector.get(import58.NavParams),this.parent.parent.parentInjector.get(import59.AlertController),this.parent.parent.parentInjector.get(import9.TranslateService),this.parent.parent.parentInjector.get(import10.WhatsSizeDatabase),this.parent.parent.parentInjector.get(import60.SizeProvider),this.parent.parent.parentInjector.get(import61.PageProvider),this.parent.parent.parentInjector.get(import11.GoogleAnalyticsProvider));
    this._appEl_2.initComponent(this._SizeView_2_4.context,([] as any[]),compView_2);
    compView_2.create(this._SizeView_2_4.context,([] as any[]),(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_0.create(this._Slide_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_3
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'entityChange',this.eventHandler(this._handle_entityChange_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import62.SizeView) && (2 === requestNodeIndex))) { return this._SizeView_2_4.context; }
    if (((token === import55.Slide) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Slide_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Slide_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_1:any = this.parent.parent.context.model.sizes[this.context.index];
    this._SizeView_2_4.check_entity(currVal_1,throwOnChange,false);
    this._SizeView_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Slide_0_4.context.ngOnDestroy();
  }
  private _handle_entityChange_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.context.model.sizes[this.context.index] = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PageHome2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageHome2(viewUtils,parentInjector,declarationEl);
}