/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pageSearch';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ng2-translate/src/translate.service';
import * as import11 from '../../providers/size';
import * as import12 from '../../db/component';
import * as import13 from '../../providers/options';
import * as import14 from '../../providers/ga';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from 'ng2-translate/src/translate.pipe';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/menu/menu-controller';
import * as import33 from 'ionic-angular/components/toolbar/toolbar';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from 'ionic-angular/components/icon/icon';
import * as import39 from 'ionic-angular/components/button/button';
import * as import40 from 'ionic-angular/components/menu/menu-toggle';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import42 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import43 from 'ionic-angular/components/navbar/navbar';
import * as import44 from '@angular/common/src/directives/ng_if';
import * as import45 from 'ionic-angular/components/content/content';
import * as import46 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import47 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import48 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import49 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import50 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import51 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import52 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import53 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import54 from 'ionic-angular/gestures/gesture-controller';
import * as import55 from 'ionic-angular/util/form';
import * as import56 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import57 from 'ionic-angular/components/label/label';
import * as import58 from '@angular/common/src/directives/ng_for';
import * as import59 from 'ionic-angular/components/select/select';
import * as import60 from '@angular/forms/src/directives/control_value_accessor';
import * as import61 from '@angular/forms/src/directives/ng_model';
import * as import62 from '@angular/forms/src/directives/ng_control';
import * as import63 from '@angular/forms/src/directives/ng_control_status';
import * as import64 from 'ionic-angular/components/item/item';
import * as import65 from 'ionic-angular/components/list/list';
import * as import66 from '@angular/forms/src/directives/ng_form';
import * as import67 from '@angular/forms/src/directives/control_container';
import * as import68 from '../../node_modules/ionic-angular/components/option/option.ngfactory';
import * as import69 from 'ionic-angular/components/option/option';
import * as import70 from '@angular/core/src/security';
export class Wrapper_PageSearch {
  context:import0.PageSearch;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.PageSearch(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PageSearch_Host:import2.RenderComponentType = (null as any);
class _View_PageSearch_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PageSearch_0_4:Wrapper_PageSearch;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch_Host0,renderType_PageSearch_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-pageSearch',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageSearch0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageSearch_0_4 = new Wrapper_PageSearch(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.TranslateService),this.parentInjector.get(import11.SizeProvider),this.parentInjector.get(import12.WhatsSizeDatabase),this.parentInjector.get(import13.SizeOptionsProvider),this.parentInjector.get(import14.GoogleAnalyticsProvider));
    this._appEl_0.initComponent(this._PageSearch_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PageSearch_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PageSearch) && (0 === requestNodeIndex))) { return this._PageSearch_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PageSearch_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PageSearch_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PageSearch_Host === (null as any))) { (renderType_PageSearch_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PageSearch_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageSearchNgFactory:import16.ComponentFactory<import0.PageSearch> = new import16.ComponentFactory<import0.PageSearch>('page-pageSearch',viewFactory_PageSearch_Host0,import0.PageSearch);
const styles_PageSearch:any[] = ([] as any[]);
var renderType_PageSearch:import2.RenderComponentType = (null as any);
class _View_PageSearch0 extends import1.AppView<import0.PageSearch> {
  _el_0:any;
  _Header_0_3:import17.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import18.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import19.Wrapper_Button;
  _MenuToggle_4_5:import20.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import21.Wrapper_ToolbarItem;
  _query_Button_4_0:import22.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import23.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import24.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import25.Wrapper_Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import26.Wrapper_NgIf;
  _text_17:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch0,renderType_PageSearch,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import19.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import19.Wrapper_Button('','',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import20.Wrapper_MenuToggle(this.parentInjector.get(import32.MenuController),new import29.ElementRef(this._el_4),this.parentInjector.get(import30.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import21.Wrapper_ToolbarItem(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import33.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import22.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import23.Wrapper_Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import24.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import24.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import33.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import25.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import25.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import3.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import37.TemplateRef_(this._appEl_16,viewFactory_PageSearch1);
    this._NgIf_16_6 = new import26.Wrapper_NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._appEl_16,
        this._text_17
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.ref);
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import39.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import40.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import41.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import42.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import43.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import33.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import37.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import44.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import45.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_9:any = this.context.model.isLoaded;
    this._NgIf_16_6.check_ngIf(currVal_9,throwOnChange,false);
    this._NgIf_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    valUnwrapper.reset();
    const currVal_7:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SEARCH.TITLE')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_7,currVal_7))) {
      this.renderer.setText(this._text_10,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PageSearch0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PageSearch> {
  if ((renderType_PageSearch === (null as any))) { (renderType_PageSearch = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_PageSearch,{})); }
  return new _View_PageSearch0(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch1 extends import1.AppView<any> {
  _el_0:any;
  _NgForm_0_3:import46.Wrapper_NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import47.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _List_2_3:import48.Wrapper_List;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Item_4_4:import49.Wrapper_Item;
  _ItemContent_4_5:import49.Wrapper_ItemContent;
  _query_Label_4_0:import22.QueryList<any>;
  _query_Button_4_1:import22.QueryList<any>;
  _query_Icon_4_2:import22.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Label_6_3:import50.Wrapper_Label;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Select_9_4:import51.Wrapper_Select;
  _NG_VALUE_ACCESSOR_9_5:any[];
  _NgModel_9_6:import52.Wrapper_NgModel;
  _NgControl_9_7:any;
  _NgControlStatus_9_8:import47.Wrapper_NgControlStatus;
  _query_Option_9_0:import22.QueryList<any>;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import53.Wrapper_NgFor;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import26.Wrapper_NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import26.Wrapper_NgIf;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import53.Wrapper_NgFor;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Item_21_4:import49.Wrapper_Item;
  _ItemContent_21_5:import49.Wrapper_ItemContent;
  _query_Label_21_0:import22.QueryList<any>;
  _query_Button_21_1:import22.QueryList<any>;
  _query_Icon_21_2:import22.QueryList<any>;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Button_23_4:import19.Wrapper_Button;
  _text_24:any;
  _el_25:any;
  _Icon_25_3:import23.Wrapper_Icon;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_8:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_30:any;
  _pipe_translate_1:import27.TranslatePipe;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch1,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'form',(null as any));
    this._NgForm_0_3 = new import46.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3.context;
    this._NgControlStatusGroup_0_5 = new import47.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_2_3 = new import48.Wrapper_List(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import54.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import49.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import49.Wrapper_Item(this.parent.parentInjector.get(import55.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer);
    this._ItemContent_4_5 = new import49.Wrapper_ItemContent();
    this._query_Label_4_0 = new import22.QueryList<any>();
    this._query_Button_4_1 = new import22.QueryList<any>();
    this._query_Icon_4_2 = new import22.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_6_3 = new import50.Wrapper_Label(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_6),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_9,'name','type');
    this._appEl_9 = new import3.AppElement(9,4,this,this._el_9);
    var compView_9:any = import51.viewFactory_Select0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Select_9_4 = new import51.Wrapper_Select(this.parent.parentInjector.get(import31.App),this.parent.parentInjector.get(import55.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_9),this.renderer,this._Item_4_4.context,this.parent.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_9_5 = [this._Select_9_4.context];
    this._NgModel_9_6 = new import52.Wrapper_NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_5);
    this._NgControl_9_7 = this._NgModel_9_6.context;
    this._NgControlStatus_9_8 = new import47.Wrapper_NgControlStatus(this._NgControl_9_7);
    this._query_Option_9_0 = new import22.QueryList<any>();
    this._appEl_9.initComponent(this._Select_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_11 = new import3.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import37.TemplateRef_(this._appEl_11,viewFactory_PageSearch2);
    this._NgFor_11_6 = new import53.Wrapper_NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parent.parentInjector.get(import56.IterableDiffers),this.parent.ref);
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_9.create(this._Select_9_4.context,([] as any[]),(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_4_0.reset([this._Label_6_3.context]);
    this._Item_4_4.context.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_6]),
      ([] as any[]).concat([
        this._text_5,
        this._text_8,
        this._text_13
      ]
      ),
      ([] as any[]).concat([this._el_9]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_15 = new import3.AppElement(15,2,this,this._anchor_15);
    this._TemplateRef_15_5 = new import37.TemplateRef_(this._appEl_15,viewFactory_PageSearch3);
    this._NgIf_15_6 = new import26.Wrapper_NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_17 = new import3.AppElement(17,2,this,this._anchor_17);
    this._TemplateRef_17_5 = new import37.TemplateRef_(this._appEl_17,viewFactory_PageSearch5);
    this._NgIf_17_6 = new import26.Wrapper_NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_19 = new import3.AppElement(19,2,this,this._anchor_19);
    this._TemplateRef_19_5 = new import37.TemplateRef_(this._appEl_19,viewFactory_PageSearch7);
    this._NgFor_19_6 = new import53.Wrapper_NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parent.parentInjector.get(import56.IterableDiffers),this.parent.ref);
    this._text_20 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','item item-block');
    this._appEl_21 = new import3.AppElement(21,2,this,this._el_21);
    var compView_21:any = import49.viewFactory_Item0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Item_21_4 = new import49.Wrapper_Item(this.parent.parentInjector.get(import55.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_21),this.renderer);
    this._ItemContent_21_5 = new import49.Wrapper_ItemContent();
    this._query_Label_21_0 = new import22.QueryList<any>();
    this._query_Button_21_1 = new import22.QueryList<any>();
    this._query_Icon_21_2 = new import22.QueryList<any>();
    this._appEl_21.initComponent(this._Item_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'block','');
    this.renderer.setElementAttribute(this._el_23,'color','danger');
    this.renderer.setElementAttribute(this._el_23,'icon-left','');
    this.renderer.setElementAttribute(this._el_23,'ion-button','');
    this.renderer.setElementAttribute(this._el_23,'type','button');
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import19.viewFactory_Button0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Button_23_4 = new import19.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_23),this.renderer);
    this._appEl_23.initComponent(this._Button_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'name','return-left');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import23.Wrapper_Icon(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText((null as any),'',(null as any));
      compView_23.create(this._Button_23_4.context,[([] as any[]).concat([
        this._text_24,
        this._el_25,
        this._text_26
      ]
    )],(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_21_0.reset(([] as any[]));
    this._Item_21_4.context.contentLabel = this._query_Label_21_0.first;
    compView_21.create(this._Item_21_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_22,
        this._el_23,
        this._text_27
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.ref);
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_9,'ngModelChange',this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_9,'keyup.space',this.eventHandler(this._handle_keyup_space_9_2.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_9_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._pipe_translate_1 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.ref);
    this._expr_31 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import57.Label) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Label_6_3.context; }
    if (((token === import37.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import58.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6.context; }
    if (((token === import59.Select) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Select_9_4.context; }
    if (((token === import60.NG_VALUE_ACCESSOR) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NG_VALUE_ACCESSOR_9_5; }
    if (((token === import61.NgModel) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgModel_9_6.context; }
    if (((token === import62.NgControl) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControl_9_7; }
    if (((token === import63.NgControlStatus) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControlStatus_9_8.context; }
    if (((token === import64.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_4_4.context; }
    if (((token === import64.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_4_5.context; }
    if (((token === import37.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import44.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import37.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import44.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    if (((token === import37.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import58.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6.context; }
    if (((token === import38.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3.context; }
    if (((token === import39.Button) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Button_23_4.context; }
    if (((token === import64.Item) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_21_4.context; }
    if (((token === import64.ItemContent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_21_5.context; }
    if (((token === import65.List) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._List_2_3.context; }
    if (((token === import66.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgForm_0_3.context; }
    if (((token === import67.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ControlContainer_0_4; }
    if (((token === import63.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._NgForm_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._List_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Item_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ItemContent_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Label_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    this._Select_9_4.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_14:any = 'type';
    this._NgModel_9_6.check_name(currVal_14,throwOnChange,false);
    const currVal_15:any = this.parent.context.model.type;
    this._NgModel_9_6.check_model(currVal_15,throwOnChange,false);
    this._NgModel_9_6.detectChangesInternal(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_8.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_22:any = this.parent.context.options.types;
    this._NgFor_11_6.check_ngForOf(currVal_22,throwOnChange,false);
    this._NgFor_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    const currVal_23:any = this.parent.context.model.type;
    this._NgIf_15_6.check_ngIf(currVal_23,throwOnChange,false);
    this._NgIf_15_6.detectChangesInternal(this,this._anchor_15,throwOnChange);
    const currVal_24:any = this.parent.context.model.sizeType;
    this._NgIf_17_6.check_ngIf(currVal_24,throwOnChange,false);
    this._NgIf_17_6.detectChangesInternal(this,this._anchor_17,throwOnChange);
    const currVal_25:any = this.parent.context.model.convertedSize;
    this._NgFor_19_6.check_ngForOf(currVal_25,throwOnChange,false);
    this._NgFor_19_6.detectChangesInternal(this,this._anchor_19,throwOnChange);
    if (this._Item_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    this._ItemContent_21_5.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_27:any = '';
    this._Button_23_4.check_block(currVal_27,throwOnChange,false);
    const currVal_28:any = 'danger';
    this._Button_23_4.check_color(currVal_28,throwOnChange,false);
    if (this._Button_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    const currVal_29:any = 'return-left';
    this._Icon_25_3.check_name(currVal_29,throwOnChange,false);
    this._Icon_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Option_9_0.dirty) {
          this._query_Option_9_0.reset([this._appEl_11.mapNestedViews(_View_PageSearch2,(nestedView:_View_PageSearch2):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_9_4.context.options = this._query_Option_9_0;
        this._query_Option_9_0.notifyOnChanges();
      }
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset(([] as any[]));
        this._Item_4_4.context._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset(([] as any[]));
        this._Item_4_4.context._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_21_1.dirty) {
        this._query_Button_21_1.reset([this._Button_23_4.context]);
        this._Item_21_4.context._buttons = this._query_Button_21_1;
        this._query_Button_21_1.notifyOnChanges();
      }
      if (this._query_Icon_21_2.dirty) {
        this._query_Icon_21_2.reset(([] as any[]));
        this._Item_21_4.context._icons = this._query_Icon_21_2;
        this._query_Icon_21_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Select_9_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_21_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = this._NgControlStatusGroup_0_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._NgControlStatusGroup_0_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_0_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_7);
      this._expr_7 = currVal_7;
    }
    valUnwrapper.reset();
    const currVal_8:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SEARCH.CAPTION_SELECT_TYPE')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_8,currVal_8))) {
      this.renderer.setText(this._text_7,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = this._Select_9_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_9,'select-disabled',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this._NgControlStatus_9_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_9,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_9_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_9,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_9_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_9,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_9_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_9,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_9_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_9,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_9_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_9,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_30:any = this._Icon_25_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_30);
      this._expr_30 = currVal_30;
    }
    valUnwrapper.reset();
    const currVal_31:any = import4.interpolate(1,'\n          ',valUnwrapper.unwrap(this._pipe_translate_1.transform('SEARCH.BUTTON_BACK')),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_31,currVal_31))) {
      this.renderer.setText(this._text_26,currVal_31);
      this._expr_31 = currVal_31;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Select_9_4.context.ngOnDestroy();
    this._NgModel_9_6.context.ngOnDestroy();
    this._Icon_25_3.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
    this._pipe_translate_1.ngOnDestroy();
  }
  private _handle_submit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.model.type = $event)) !== false);
    const pd_1:any = ((<any>this.parent.context.onChangeType($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_9_1($event:any):boolean {
    this._appEl_9.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_9_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_9_2($event:any):boolean {
    this._appEl_9.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_9_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goHome()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PageSearch1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch1(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch2 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import68.Wrapper_Option;
  _text_1:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch2,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import68.Wrapper_Option(new import29.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.parent.ref);
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import69.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = this.context.$implicit.value;
    this._Option_0_3.check_value(currVal_0,throwOnChange,false);
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_1:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform(this.context.$implicit.text)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PageSearch1>this.parent)._query_Option_9_0.setDirty();
  }
  destroyInternal():void {
    this._pipe_translate_0.ngOnDestroy();
  }
}
function viewFactory_PageSearch2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch2(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import49.Wrapper_Item;
  _ItemContent_0_5:import49.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import50.Wrapper_Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Select_5_4:import51.Wrapper_Select;
  _NG_VALUE_ACCESSOR_5_5:any[];
  _NgModel_5_6:import52.Wrapper_NgModel;
  _NgControl_5_7:any;
  _NgControlStatus_5_8:import47.Wrapper_NgControlStatus;
  _query_Option_5_0:import22.QueryList<any>;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _TemplateRef_7_5:any;
  _NgFor_7_6:import53.Wrapper_NgFor;
  _text_8:any;
  _text_9:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch3,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import49.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import49.Wrapper_Item(this.parent.parent.parentInjector.get(import55.Form),this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import49.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import50.Wrapper_Label(this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_5,'name','sizeType');
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import51.viewFactory_Select0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Select_5_4 = new import51.Wrapper_Select(this.parent.parent.parentInjector.get(import31.App),this.parent.parent.parentInjector.get(import55.Form),this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_5),this.renderer,this._Item_0_4.context,this.parent.parent.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_5_5 = [this._Select_5_4.context];
    this._NgModel_5_6 = new import52.Wrapper_NgModel((<_View_PageSearch1>this.parent)._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_5_5);
    this._NgControl_5_7 = this._NgModel_5_6.context;
    this._NgControlStatus_5_8 = new import47.Wrapper_NgControlStatus(this._NgControl_5_7);
    this._query_Option_5_0 = new import22.QueryList<any>();
    this._appEl_5.initComponent(this._Select_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_7 = new import3.AppElement(7,5,this,this._anchor_7);
    this._TemplateRef_7_5 = new import37.TemplateRef_(this._appEl_7,viewFactory_PageSearch4);
    this._NgFor_7_6 = new import53.Wrapper_NgFor(this._appEl_7.vcRef,this._TemplateRef_7_5,this.parent.parent.parentInjector.get(import56.IterableDiffers),this.parent.parent.ref);
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_5.create(this._Select_5_4.context,([] as any[]),(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3.context]);
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._text_1,
        this._text_4,
        this._text_9
      ]
      ),
      ([] as any[]).concat([this._el_5]),
      ([] as any[])
    ]
    ,(null as any));
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.parent.ref);
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'ngModelChange',this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_5,'keyup.space',this.eventHandler(this._handle_keyup_space_5_2.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_5_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import57.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3.context; }
    if (((token === import37.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import58.NgFor) && (7 === requestNodeIndex))) { return this._NgFor_7_6.context; }
    if (((token === import59.Select) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Select_5_4.context; }
    if (((token === import60.NG_VALUE_ACCESSOR) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NG_VALUE_ACCESSOR_5_5; }
    if (((token === import61.NgModel) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgModel_5_6.context; }
    if (((token === import62.NgControl) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgControl_5_7; }
    if (((token === import63.NgControlStatus) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgControlStatus_5_8.context; }
    if (((token === import64.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_0_4.context; }
    if (((token === import64.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Label_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Select_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'sizeType';
    this._NgModel_5_6.check_name(currVal_6,throwOnChange,false);
    const currVal_7:any = this.parent.parent.context.model.sizeType;
    this._NgModel_5_6.check_model(currVal_7,throwOnChange,false);
    this._NgModel_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    this._NgControlStatus_5_8.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_14:any = this.parent.parent.context.model.sizeTypes;
    this._NgFor_7_6.check_ngForOf(currVal_14,throwOnChange,false);
    this._NgFor_7_6.detectChangesInternal(this,this._anchor_7,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Option_5_0.dirty) {
          this._query_Option_5_0.reset([this._appEl_7.mapNestedViews(_View_PageSearch4,(nestedView:_View_PageSearch4):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_5_4.context.options = this._query_Option_5_0;
        this._query_Option_5_0.notifyOnChanges();
      }
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Select_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SEARCH.CAPTION_SELECT_CLOTHING')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_5:any = this._Select_5_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_5,'select-disabled',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._NgControlStatus_5_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_5_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_5_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_5_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_5_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_5_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Select_5_4.context.ngOnDestroy();
    this._NgModel_5_6.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
  }
  private _handle_ngModelChange_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.context.model.sizeType = $event)) !== false);
    const pd_1:any = ((<any>this.parent.parent.context.onChangeSizeType($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_5_1($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_5_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_5_2($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_5_4.context._keyup()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PageSearch3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch3(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch4 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import68.Wrapper_Option;
  _text_1:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch4,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import68.Wrapper_Option(new import29.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.parent.parent.ref);
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import69.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = this.context.$implicit.value;
    this._Option_0_3.check_value(currVal_0,throwOnChange,false);
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_1:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform(this.context.$implicit.text)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PageSearch3>this.parent)._query_Option_5_0.setDirty();
  }
  destroyInternal():void {
    this._pipe_translate_0.ngOnDestroy();
  }
}
function viewFactory_PageSearch4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch4(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import49.Wrapper_Item;
  _ItemContent_0_5:import49.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import50.Wrapper_Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Select_5_4:import51.Wrapper_Select;
  _NG_VALUE_ACCESSOR_5_5:any[];
  _NgModel_5_6:import52.Wrapper_NgModel;
  _NgControl_5_7:any;
  _NgControlStatus_5_8:import47.Wrapper_NgControlStatus;
  _query_Option_5_0:import22.QueryList<any>;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _TemplateRef_7_5:any;
  _NgFor_7_6:import53.Wrapper_NgFor;
  _text_8:any;
  _text_9:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch5,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import49.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import49.Wrapper_Item(this.parent.parent.parentInjector.get(import55.Form),this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import49.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import50.Wrapper_Label(this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_5,'name','size');
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import51.viewFactory_Select0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Select_5_4 = new import51.Wrapper_Select(this.parent.parent.parentInjector.get(import31.App),this.parent.parent.parentInjector.get(import55.Form),this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_5),this.renderer,this._Item_0_4.context,this.parent.parent.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_5_5 = [this._Select_5_4.context];
    this._NgModel_5_6 = new import52.Wrapper_NgModel((<_View_PageSearch1>this.parent)._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_5_5);
    this._NgControl_5_7 = this._NgModel_5_6.context;
    this._NgControlStatus_5_8 = new import47.Wrapper_NgControlStatus(this._NgControl_5_7);
    this._query_Option_5_0 = new import22.QueryList<any>();
    this._appEl_5.initComponent(this._Select_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_7 = new import3.AppElement(7,5,this,this._anchor_7);
    this._TemplateRef_7_5 = new import37.TemplateRef_(this._appEl_7,viewFactory_PageSearch6);
    this._NgFor_7_6 = new import53.Wrapper_NgFor(this._appEl_7.vcRef,this._TemplateRef_7_5,this.parent.parent.parentInjector.get(import56.IterableDiffers),this.parent.parent.ref);
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_5.create(this._Select_5_4.context,([] as any[]),(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3.context]);
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._text_1,
        this._text_4,
        this._text_9
      ]
      ),
      ([] as any[]).concat([this._el_5]),
      ([] as any[])
    ]
    ,(null as any));
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.parent.ref);
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'ngModelChange',this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_5,'keyup.space',this.eventHandler(this._handle_keyup_space_5_2.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_5_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import57.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3.context; }
    if (((token === import37.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import58.NgFor) && (7 === requestNodeIndex))) { return this._NgFor_7_6.context; }
    if (((token === import59.Select) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Select_5_4.context; }
    if (((token === import60.NG_VALUE_ACCESSOR) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NG_VALUE_ACCESSOR_5_5; }
    if (((token === import61.NgModel) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgModel_5_6.context; }
    if (((token === import62.NgControl) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgControl_5_7; }
    if (((token === import63.NgControlStatus) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgControlStatus_5_8.context; }
    if (((token === import64.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_0_4.context; }
    if (((token === import64.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Label_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Select_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'size';
    this._NgModel_5_6.check_name(currVal_6,throwOnChange,false);
    const currVal_7:any = this.parent.parent.context.model.size;
    this._NgModel_5_6.check_model(currVal_7,throwOnChange,false);
    this._NgModel_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    this._NgControlStatus_5_8.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_14:any = this.parent.parent.context.model.availableSizes;
    this._NgFor_7_6.check_ngForOf(currVal_14,throwOnChange,false);
    this._NgFor_7_6.detectChangesInternal(this,this._anchor_7,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Option_5_0.dirty) {
          this._query_Option_5_0.reset([this._appEl_7.mapNestedViews(_View_PageSearch6,(nestedView:_View_PageSearch6):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_5_4.context.options = this._query_Option_5_0;
        this._query_Option_5_0.notifyOnChanges();
      }
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Select_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SEARCH.CAPTION_SELECT_SIZES')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_5:any = this._Select_5_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_5,'select-disabled',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._NgControlStatus_5_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_5_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_5_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_5_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_5_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_5_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Select_5_4.context.ngOnDestroy();
    this._NgModel_5_6.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
  }
  private _handle_ngModelChange_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.context.model.size = $event)) !== false);
    const pd_1:any = ((<any>this.parent.parent.context.onChangeSize($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_5_1($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_5_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_5_2($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_5_4.context._keyup()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PageSearch5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch5(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch6 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import68.Wrapper_Option;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch6,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import68.Wrapper_Option(new import29.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import69.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    this._Option_0_3.check_value(currVal_0,throwOnChange,false);
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PageSearch5>this.parent)._query_Option_5_0.setDirty();
  }
}
function viewFactory_PageSearch6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch6(viewUtils,parentInjector,declarationEl);
}
class _View_PageSearch7 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import49.Wrapper_Item;
  _ItemContent_0_5:import49.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  _pipe_translate_0:import27.TranslatePipe;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSearch7,renderType_PageSearch,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import49.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import49.Wrapper_Item(this.parent.parent.parentInjector.get(import55.Form),this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import49.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','flag');
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'large','');
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3,
        this._el_4,
        this._text_6,
        this._el_7,
        this._text_9
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import27.TranslatePipe(this.parentInjector.get(import10.TranslateService),this.parent.parent.ref);
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import64.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_0_4.context; }
    if (((token === import64.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.flag;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import70.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    valUnwrapper.reset();
    const currVal_1:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform(this.context.$implicit.text)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.value,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_translate_0.ngOnDestroy();
  }
}
function viewFactory_PageSearch7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSearch7(viewUtils,parentInjector,declarationEl);
}