/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pageSizes';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '../../db/component';
import * as import12 from '../../providers/size';
import * as import13 from '../../providers/page';
import * as import14 from '../../providers/ga';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import26 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import29 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import30 from 'ng2-translate/src/translate.pipe';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from 'ionic-angular/components/app/app';
import * as import35 from 'ionic-angular/components/menu/menu-controller';
import * as import36 from 'ionic-angular/components/toolbar/toolbar';
import * as import37 from 'ionic-angular/util/keyboard';
import * as import38 from '@angular/core/src/zone/ng_zone';
import * as import39 from 'ionic-angular/components/tabs/tabs';
import * as import40 from '@angular/core/src/linker/template_ref';
import * as import41 from 'ng2-translate/src/translate.service';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from 'ionic-angular/components/button/button';
import * as import44 from 'ionic-angular/components/menu/menu-toggle';
import * as import45 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import46 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import47 from 'ionic-angular/components/navbar/navbar';
import * as import48 from 'ionic-angular/components/grid/grid';
import * as import49 from '@angular/common/src/directives/ng_if';
import * as import50 from '@angular/forms/src/directives/ng_form';
import * as import51 from '@angular/forms/src/directives/control_container';
import * as import52 from '@angular/forms/src/directives/ng_control_status';
import * as import53 from 'ionic-angular/components/content/content';
import * as import54 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import55 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import56 from 'ionic-angular/gestures/gesture-controller';
import * as import57 from 'ionic-angular/util/form';
import * as import58 from 'ionic-angular/components/item/item';
import * as import59 from 'ionic-angular/components/list/list';
import * as import60 from '../../node_modules/ionic-angular/components/radio/radio-group.ngfactory';
import * as import61 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import62 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import63 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import64 from '@angular/common/src/directives/ng_for';
import * as import65 from 'ionic-angular/components/radio/radio-group';
import * as import66 from '@angular/forms/src/directives/control_value_accessor';
import * as import67 from '@angular/forms/src/directives/ng_model';
import * as import68 from '@angular/forms/src/directives/ng_control';
export class Wrapper_PageSizes {
  context:import0.PageSizes;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.PageSizes(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PageSizes_Host:import2.RenderComponentType = (null as any);
class _View_PageSizes_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PageSizes_0_4:Wrapper_PageSizes;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSizes_Host0,renderType_PageSizes_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-pageSizes',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageSizes0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageSizes_0_4 = new Wrapper_PageSizes(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.WhatsSizeDatabase),this.parentInjector.get(import12.SizeProvider),this.parentInjector.get(import13.PageProvider),this.parentInjector.get(import14.GoogleAnalyticsProvider));
    this._appEl_0.initComponent(this._PageSizes_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PageSizes_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PageSizes) && (0 === requestNodeIndex))) { return this._PageSizes_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PageSizes_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PageSizes_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PageSizes_Host === (null as any))) { (renderType_PageSizes_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PageSizes_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageSizesNgFactory:import16.ComponentFactory<import0.PageSizes> = new import16.ComponentFactory<import0.PageSizes>('page-pageSizes',viewFactory_PageSizes_Host0,import0.PageSizes);
const styles_PageSizes:any[] = ([] as any[]);
var renderType_PageSizes:import2.RenderComponentType = (null as any);
class _View_PageSizes0 extends import1.AppView<import0.PageSizes> {
  _el_0:any;
  _Header_0_3:import17.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import18.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import19.Wrapper_Button;
  _MenuToggle_4_5:import20.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import21.Wrapper_ToolbarItem;
  _query_Button_4_0:import22.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import23.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import24.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import25.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _NgForm_16_3:import26.Wrapper_NgForm;
  _ControlContainer_16_4:any;
  _NgControlStatusGroup_16_5:import27.Wrapper_NgControlStatusGroup;
  _text_17:any;
  _el_18:any;
  _Grid_18_3:import28.Wrapper_Grid;
  _text_19:any;
  _el_20:any;
  _Row_20_3:import28.Wrapper_Row;
  _text_21:any;
  _el_22:any;
  _Col_22_3:import28.Wrapper_Col;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Button_24_4:import19.Wrapper_Button;
  _text_25:any;
  _el_26:any;
  _Icon_26_3:import23.Wrapper_Icon;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _Row_31_3:import28.Wrapper_Row;
  _text_32:any;
  _el_33:any;
  _Col_33_3:import28.Wrapper_Col;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import29.Wrapper_NgIf;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import29.Wrapper_NgIf;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _Row_41_3:import28.Wrapper_Row;
  _text_42:any;
  _el_43:any;
  _Col_43_3:import28.Wrapper_Col;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _Button_45_4:import19.Wrapper_Button;
  _text_46:any;
  _el_47:any;
  _Icon_47_3:import23.Wrapper_Icon;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  _pipe_translate_0:import30.TranslatePipe;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_20:any;
  _pipe_translate_1:import30.TranslatePipe;
  /*private*/ _expr_21:any;
  /*private*/ _expr_28:any;
  _pipe_translate_2:import30.TranslatePipe;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSizes0,renderType_PageSizes,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Wrapper_Header(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import33.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import34.App),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import19.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import19.Wrapper_Button('','',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import20.Wrapper_MenuToggle(this.parentInjector.get(import35.MenuController),new import32.ElementRef(this._el_4),this.parentInjector.get(import33.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import21.Wrapper_ToolbarItem(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import36.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import22.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import23.Wrapper_Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import24.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import24.Wrapper_ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import36.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import25.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import25.Wrapper_Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import34.App),this.parentInjector.get(import37.Keyboard),this.parentInjector.get(import38.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import39.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'form',(null as any));
    this._NgForm_16_3 = new import26.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_16_4 = this._NgForm_16_3.context;
    this._NgControlStatusGroup_16_5 = new import27.Wrapper_NgControlStatusGroup(this._ControlContainer_16_4);
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-grid',(null as any));
    this._Grid_18_3 = new import28.Wrapper_Grid();
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-row',(null as any));
    this._Row_20_3 = new import28.Wrapper_Row();
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_22,'width-100','');
    this._Col_22_3 = new import28.Wrapper_Col();
    this._text_23 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'block','');
    this.renderer.setElementAttribute(this._el_24,'green','');
    this.renderer.setElementAttribute(this._el_24,'icon-left','');
    this.renderer.setElementAttribute(this._el_24,'ion-button','');
    this.renderer.setElementAttribute(this._el_24,'type','button');
    this._appEl_24 = new import3.AppElement(24,22,this,this._el_24);
    var compView_24:any = import19.viewFactory_Button0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Button_24_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_24),this.renderer);
    this._appEl_24.initComponent(this._Button_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_26,'name','add');
    this.renderer.setElementAttribute(this._el_26,'role','img');
    this._Icon_26_3 = new import23.Wrapper_Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText((null as any),'',(null as any));
      compView_24.create(this._Button_24_4.context,[([] as any[]).concat([
        this._text_25,
        this._el_26,
        this._text_27
      ]
    )],(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._text_30 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_18,'ion-row',(null as any));
    this._Row_31_3 = new import28.Wrapper_Row();
    this._text_32 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_33,'width-100','');
    this._Col_33_3 = new import28.Wrapper_Col();
    this._text_34 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_35 = new import3.AppElement(35,33,this,this._anchor_35);
    this._TemplateRef_35_5 = new import40.TemplateRef_(this._appEl_35,viewFactory_PageSizes1);
    this._NgIf_35_6 = new import29.Wrapper_NgIf(this._appEl_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_37 = new import3.AppElement(37,33,this,this._anchor_37);
    this._TemplateRef_37_5 = new import40.TemplateRef_(this._appEl_37,viewFactory_PageSizes2);
    this._NgIf_37_6 = new import29.Wrapper_NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_39 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._text_40 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_18,'ion-row',(null as any));
    this._Row_41_3 = new import28.Wrapper_Row();
    this._text_42 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_43,'width-100','');
    this._Col_43_3 = new import28.Wrapper_Col();
    this._text_44 = this.renderer.createText(this._el_43,'\n          ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'button',(null as any));
    this.renderer.setElementAttribute(this._el_45,'block','');
    this.renderer.setElementAttribute(this._el_45,'color','danger');
    this.renderer.setElementAttribute(this._el_45,'icon-left','');
    this.renderer.setElementAttribute(this._el_45,'ion-button','');
    this.renderer.setElementAttribute(this._el_45,'type','button');
    this._appEl_45 = new import3.AppElement(45,43,this,this._el_45);
    var compView_45:any = import19.viewFactory_Button0(this.viewUtils,this.injector(45),this._appEl_45);
    this._Button_45_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_45),this.renderer);
    this._appEl_45.initComponent(this._Button_45_4.context,([] as any[]),compView_45);
    this._text_46 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_47,'name','return-left');
    this.renderer.setElementAttribute(this._el_47,'role','img');
    this._Icon_47_3 = new import23.Wrapper_Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_47),this.renderer);
    this._text_48 = this.renderer.createText((null as any),'',(null as any));
      compView_45.create(this._Button_45_4.context,[([] as any[]).concat([
        this._text_46,
        this._el_47,
        this._text_48
      ]
    )],(null as any));
    this._text_49 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._text_50 = this.renderer.createText(this._el_41,'\n      ',(null as any));
    this._text_51 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_52 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_53
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import30.TranslatePipe(this.parentInjector.get(import41.TranslateService),this.ref);
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_16,'submit',this.eventHandler(this._handle_submit_16_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_16,'reset',this.eventHandler(this._handle_reset_16_1.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this._pipe_translate_1 = new import30.TranslatePipe(this.parentInjector.get(import41.TranslateService),this.ref);
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_45,'click',this.eventHandler(this._handle_click_45_0.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this._pipe_translate_2 = new import30.TranslatePipe(this.parentInjector.get(import41.TranslateService),this.ref);
    this._expr_29 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import43.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import44.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import45.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import46.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import47.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import36.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import42.Icon) && (26 === requestNodeIndex))) { return this._Icon_26_3.context; }
    if (((token === import43.Button) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Button_24_4.context; }
    if (((token === import48.Col) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Col_22_3.context; }
    if (((token === import48.Row) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Row_20_3.context; }
    if (((token === import40.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import49.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6.context; }
    if (((token === import40.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import49.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6.context; }
    if (((token === import48.Col) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Col_33_3.context; }
    if (((token === import48.Row) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Row_31_3.context; }
    if (((token === import42.Icon) && (47 === requestNodeIndex))) { return this._Icon_47_3.context; }
    if (((token === import43.Button) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Button_45_4.context; }
    if (((token === import48.Col) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Col_43_3.context; }
    if (((token === import48.Row) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Row_41_3.context; }
    if (((token === import48.Grid) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Grid_18_3.context; }
    if (((token === import50.NgForm) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgForm_16_3.context; }
    if (((token === import51.ControlContainer) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ControlContainer_16_4; }
    if (((token === import52.NgControlStatusGroup) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgControlStatusGroup_16_5.context; }
    if (((token === import53.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._NgForm_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._NgControlStatusGroup_16_5.detectChangesInternal(this,this._el_16,throwOnChange);
    this._Grid_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._Row_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._Col_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_18:any = '';
    this._Button_24_4.check_block(currVal_18,throwOnChange,false);
    if (this._Button_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    const currVal_19:any = 'add';
    this._Icon_26_3.check_name(currVal_19,throwOnChange,false);
    this._Icon_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Row_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this._Col_33_3.detectChangesInternal(this,this._el_33,throwOnChange);
    const currVal_22:any = (this.context.model.sizes.length === 0);
    this._NgIf_35_6.check_ngIf(currVal_22,throwOnChange,false);
    this._NgIf_35_6.detectChangesInternal(this,this._anchor_35,throwOnChange);
    const currVal_23:any = (this.context.model.sizes.length > 0);
    this._NgIf_37_6.check_ngIf(currVal_23,throwOnChange,false);
    this._NgIf_37_6.detectChangesInternal(this,this._anchor_37,throwOnChange);
    this._Row_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Col_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_25:any = '';
    this._Button_45_4.check_block(currVal_25,throwOnChange,false);
    const currVal_26:any = 'danger';
    this._Button_45_4.check_color(currVal_26,throwOnChange,false);
    if (this._Button_45_4.detectChangesInternal(this,this._el_45,throwOnChange)) { this._appEl_45.componentView.markAsCheckOnce(); }
    const currVal_27:any = 'return-left';
    this._Icon_47_3.check_name(currVal_27,throwOnChange,false);
    this._Icon_47_3.detectChangesInternal(this,this._el_47,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_24_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_45_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    valUnwrapper.reset();
    const currVal_7:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SIZE.TITLE')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_7,currVal_7))) {
      this.renderer.setText(this._text_10,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._NgControlStatusGroup_16_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_16_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_16_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatusGroup_16_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatusGroup_16_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatusGroup_16_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_20:any = this._Icon_26_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_26,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    valUnwrapper.reset();
    const currVal_21:any = import4.interpolate(1,'\n            ',valUnwrapper.unwrap(this._pipe_translate_1.transform('SIZE.BUTTONS.NEW')),'\n          ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_21,currVal_21))) {
      this.renderer.setText(this._text_27,currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_28:any = this._Icon_47_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_47,'hide',currVal_28);
      this._expr_28 = currVal_28;
    }
    valUnwrapper.reset();
    const currVal_29:any = import4.interpolate(1,'\n            ',valUnwrapper.unwrap(this._pipe_translate_2.transform('SIZE.BUTTONS.BACK')),'\n          ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_29,currVal_29))) {
      this.renderer.setText(this._text_48,currVal_29);
      this._expr_29 = currVal_29;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_26_3.context.ngOnDestroy();
    this._Icon_47_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
    this._pipe_translate_1.ngOnDestroy();
    this._pipe_translate_2.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_16_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_16_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToSizeForm()) !== false);
    return (true && pd_0);
  }
  private _handle_click_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goHome()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PageSizes0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PageSizes> {
  if ((renderType_PageSizes === (null as any))) { (renderType_PageSizes = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_PageSizes,{})); }
  return new _View_PageSizes0(viewUtils,parentInjector,declarationEl);
}
class _View_PageSizes1 extends import1.AppView<any> {
  _el_0:any;
  _List_0_3:import54.Wrapper_List;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import55.Wrapper_Item;
  _ItemContent_2_5:import55.Wrapper_ItemContent;
  _query_Label_2_0:import22.QueryList<any>;
  _query_Button_2_1:import22.QueryList<any>;
  _query_Icon_2_2:import22.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _pipe_translate_0:import30.TranslatePipe;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSizes1,renderType_PageSizes,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_0_3 = new import54.Wrapper_List(this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import56.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import55.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import55.Wrapper_Item(this.parent.parentInjector.get(import57.Form),this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import55.Wrapper_ItemContent();
    this._query_Label_2_0 = new import22.QueryList<any>();
    this._query_Button_2_1 = new import22.QueryList<any>();
    this._query_Icon_2_2 = new import22.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'h5',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._pipe_translate_0 = new import30.TranslatePipe(this.parentInjector.get(import41.TranslateService),this.parent.ref);
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import58.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_2_4.context; }
    if (((token === import58.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_2_5.context; }
    if (((token === import59.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_translate_0.transform('SIZE.ALERTS.GRIDEMPTY')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_translate_0.ngOnDestroy();
  }
}
function viewFactory_PageSizes1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSizes1(viewUtils,parentInjector,declarationEl);
}
class _View_PageSizes2 extends import1.AppView<any> {
  _el_0:any;
  _RadioGroup_0_3:import60.Wrapper_RadioGroup;
  _NG_VALUE_ACCESSOR_0_4:any[];
  _NgModel_0_5:import61.Wrapper_NgModel;
  _NgControl_0_6:any;
  _NgControlStatus_0_7:import27.Wrapper_NgControlStatus;
  _List_0_8:import54.Wrapper_List;
  _query_ListHeader_0_0:import22.QueryList<any>;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import62.Wrapper_NgFor;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSizes2,renderType_PageSizes,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_0,'name','size');
    this.renderer.setElementAttribute(this._el_0,'radio-group','');
    this.renderer.setElementAttribute(this._el_0,'role','radiogroup');
    this._RadioGroup_0_3 = new import60.Wrapper_RadioGroup(this.renderer,new import32.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_4 = [this._RadioGroup_0_3.context];
    this._NgModel_0_5 = new import61.Wrapper_NgModel((<_View_PageSizes0>this.parent)._ControlContainer_16_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_4);
    this._NgControl_0_6 = this._NgModel_0_5.context;
    this._NgControlStatus_0_7 = new import27.Wrapper_NgControlStatus(this._NgControl_0_6);
    this._List_0_8 = new import54.Wrapper_List(this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import56.GestureController));
    this._query_ListHeader_0_0 = new import22.QueryList<any>();
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import40.TemplateRef_(this._appEl_2,viewFactory_PageSizes3);
    this._NgFor_2_6 = new import62.Wrapper_NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import63.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._query_ListHeader_0_0.reset(([] as any[]));
    this._RadioGroup_0_3.context._header = this._query_ListHeader_0_0.first;
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngModelChange',this.eventHandler(this._handle_ngModelChange_0_0.bind(this)));
    const subscription_0:any = this._NgModel_0_5.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import64.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    if (((token === import65.RadioGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RadioGroup_0_3.context; }
    if (((token === import66.NG_VALUE_ACCESSOR) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import67.NgModel) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgModel_0_5.context; }
    if (((token === import68.NgControl) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgControl_0_6; }
    if (((token === import52.NgControlStatus) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgControlStatus_0_7.context; }
    if (((token === import59.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._List_0_8.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RadioGroup_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = 'size';
    this._NgModel_0_5.check_name(currVal_2,throwOnChange,false);
    const currVal_3:any = this.parent.context.model.size;
    this._NgModel_0_5.check_model(currVal_3,throwOnChange,false);
    this._NgModel_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_7.detectChangesInternal(this,this._el_0,throwOnChange);
    this._List_0_8.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_10:any = this.parent.context.model.sizes;
    this._NgFor_2_6.check_ngForOf(currVal_10,throwOnChange,false);
    this._NgFor_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._RadioGroup_0_3.context.ngAfterContentInit(); } }
    const currVal_4:any = this._NgControlStatus_0_7.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_0_7.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_0_7.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_0_7.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_0_7.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_0_7.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_5.context.ngOnDestroy();
  }
  private _handle_ngModelChange_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.model.size = $event)) !== false);
    const pd_1:any = ((<any>this.parent.context.onSelectedSize($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_PageSizes2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSizes2(viewUtils,parentInjector,declarationEl);
}
class _View_PageSizes3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import55.Wrapper_Item;
  _ItemContent_0_5:import55.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import19.Wrapper_Button;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import23.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Button_10_4:import19.Wrapper_Button;
  _text_11:any;
  _el_12:any;
  _Icon_12_3:import23.Wrapper_Icon;
  _text_13:any;
  _text_14:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  _pipe_translate_0:import30.TranslatePipe;
  /*private*/ _expr_5:any;
  /*private*/ _expr_9:any;
  _pipe_translate_1:import30.TranslatePipe;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PageSizes3,renderType_PageSizes,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import55.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import55.Wrapper_Item(this.parent.parent.parentInjector.get(import57.Form),this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import55.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'icon-left','');
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'item-right','');
    this.renderer.setElementAttribute(this._el_5,'outline','');
    this.renderer.setElementAttribute(this._el_5,'type','button');
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import19.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import19.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_5),this.renderer);
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','md-create');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import23.Wrapper_Icon(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'icon-left','');
    this.renderer.setElementAttribute(this._el_10,'ion-button','');
    this.renderer.setElementAttribute(this._el_10,'item-right','');
    this.renderer.setElementAttribute(this._el_10,'outline','');
    this.renderer.setElementAttribute(this._el_10,'type','button');
    this._appEl_10 = new import3.AppElement(10,0,this,this._el_10);
    var compView_10:any = import19.viewFactory_Button0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Button_10_4 = new import19.Wrapper_Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Button_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_12,'name','trash');
    this.renderer.setElementAttribute(this._el_12,'role','img');
    this._Icon_12_3 = new import23.Wrapper_Icon(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText((null as any),'',(null as any));
      compView_10.create(this._Button_10_4.context,[([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_13
      ]
    )],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._text_9,
        this._text_14
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._el_5,
        this._el_10
      ]
      )
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._pipe_translate_0 = new import30.TranslatePipe(this.parentInjector.get(import41.TranslateService),this.parent.parent.ref);
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._pipe_translate_1 = new import30.TranslatePipe(this.parentInjector.get(import41.TranslateService),this.parent.parent.ref);
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import43.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import42.Icon) && (12 === requestNodeIndex))) { return this._Icon_12_3.context; }
    if (((token === import43.Button) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_10_4.context; }
    if (((token === import58.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_0_4.context; }
    if (((token === import58.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._Button_5_4.check_outline(currVal_2,throwOnChange,false);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'md-create';
    this._Icon_7_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_7:any = '';
    this._Button_10_4.check_outline(currVal_7,throwOnChange,false);
    if (this._Button_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'trash';
    this._Icon_12_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([
          this._Button_5_4.context,
          this._Button_10_4.context
        ]
        );
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.personName,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    valUnwrapper.reset();
    const currVal_5:any = import4.interpolate(1,' ',valUnwrapper.unwrap(this._pipe_translate_0.transform('SIZE.BUTTONS.EDIT')),'\n              ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_5,currVal_5))) {
      this.renderer.setText(this._text_8,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_9:any = this._Icon_12_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_12,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    valUnwrapper.reset();
    const currVal_10:any = import4.interpolate(1,' ',valUnwrapper.unwrap(this._pipe_translate_1.transform('SIZE.BUTTONS.DELETE')),'\n              ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_10,currVal_10))) {
      this.renderer.setText(this._text_13,currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_12_3.context.ngOnDestroy();
    this._pipe_translate_0.ngOnDestroy();
    this._pipe_translate_1.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.editSize(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.deleteSize(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PageSizes3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PageSizes3(viewUtils,parentInjector,declarationEl);
}